{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Request.ApiregistrationV1beta1 exposing (createApiregistrationV1beta1APIService, deleteApiregistrationV1beta1APIService, deleteApiregistrationV1beta1CollectionAPIService, getApiregistrationV1beta1APIResources, listApiregistrationV1beta1APIService, patchApiregistrationV1beta1APIService, patchApiregistrationV1beta1APIServiceStatus, readApiregistrationV1beta1APIService, readApiregistrationV1beta1APIServiceStatus, replaceApiregistrationV1beta1APIService, replaceApiregistrationV1beta1APIServiceStatus, watchApiregistrationV1beta1APIService, watchApiregistrationV1beta1APIServiceList)

import Data.IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIService exposing (IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIService, ioK8sKubeAggregatorPkgApisApiregistrationV1beta1APIServiceDecoder, ioK8sKubeAggregatorPkgApisApiregistrationV1beta1APIServiceEncoder)
import Data.IoK8sApimachineryPkgApisMetaV1DeleteOptions exposing (IoK8sApimachineryPkgApisMetaV1DeleteOptions, ioK8sApimachineryPkgApisMetaV1DeleteOptionsEncoder)
import Data.IoK8sApimachineryPkgApisMetaV1Status exposing (IoK8sApimachineryPkgApisMetaV1Status, ioK8sApimachineryPkgApisMetaV1StatusDecoder)
import Data.IoK8sApimachineryPkgApisMetaV1APIResourceList exposing (IoK8sApimachineryPkgApisMetaV1APIResourceList, ioK8sApimachineryPkgApisMetaV1APIResourceListDecoder)
import Data.IoK8sApimachineryPkgApisMetaV1Patch exposing (IoK8sApimachineryPkgApisMetaV1Patch, ioK8sApimachineryPkgApisMetaV1PatchEncoder)
import Data.IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIServiceList exposing (IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIServiceList, ioK8sKubeAggregatorPkgApisApiregistrationV1beta1APIServiceListDecoder)
import Data.IoK8sApimachineryPkgApisMetaV1WatchEvent exposing (IoK8sApimachineryPkgApisMetaV1WatchEvent, ioK8sApimachineryPkgApisMetaV1WatchEventDecoder)
import Http
import Json.Decode as Decode


basePath : String
basePath =
    "https://localhost"


{-
   create an APIService
-}
createApiregistrationV1beta1APIService : IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIService -> Http.Request IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIService
createApiregistrationV1beta1APIService model =
    { method = "POST"
    , url = basePath ++ "/apis/apiregistration.k8s.io/v1beta1/apiservices"
    , headers = []
    , body = Http.jsonBody <| ioK8sKubeAggregatorPkgApisApiregistrationV1beta1APIServiceEncoder model
    , expect = Http.expectJson ioK8sKubeAggregatorPkgApisApiregistrationV1beta1APIServiceDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   delete an APIService
-}
deleteApiregistrationV1beta1APIService : String -> IoK8sApimachineryPkgApisMetaV1DeleteOptions -> Http.Request IoK8sApimachineryPkgApisMetaV1Status
deleteApiregistrationV1beta1APIService name model =
    { method = "DELETE"
    , url = basePath ++ "/apis/apiregistration.k8s.io/v1beta1/apiservices/" ++ name
    , headers = []
    , body = Http.jsonBody <| ioK8sApimachineryPkgApisMetaV1DeleteOptionsEncoder model
    , expect = Http.expectJson ioK8sApimachineryPkgApisMetaV1StatusDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   delete collection of APIService
-}
deleteApiregistrationV1beta1CollectionAPIService : Http.Request IoK8sApimachineryPkgApisMetaV1Status
deleteApiregistrationV1beta1CollectionAPIService =
    { method = "DELETE"
    , url = basePath ++ "/apis/apiregistration.k8s.io/v1beta1/apiservices"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson ioK8sApimachineryPkgApisMetaV1StatusDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   get available resources
-}
getApiregistrationV1beta1APIResources : Http.Request IoK8sApimachineryPkgApisMetaV1APIResourceList
getApiregistrationV1beta1APIResources =
    { method = "GET"
    , url = basePath ++ "/apis/apiregistration.k8s.io/v1beta1/"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson ioK8sApimachineryPkgApisMetaV1APIResourceListDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   list or watch objects of kind APIService
-}
listApiregistrationV1beta1APIService : Http.Request IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIServiceList
listApiregistrationV1beta1APIService =
    { method = "GET"
    , url = basePath ++ "/apis/apiregistration.k8s.io/v1beta1/apiservices"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson ioK8sKubeAggregatorPkgApisApiregistrationV1beta1APIServiceListDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   partially update the specified APIService
-}
patchApiregistrationV1beta1APIService : String -> IoK8sApimachineryPkgApisMetaV1Patch -> Http.Request IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIService
patchApiregistrationV1beta1APIService name model =
    { method = "PATCH"
    , url = basePath ++ "/apis/apiregistration.k8s.io/v1beta1/apiservices/" ++ name
    , headers = []
    , body = Http.jsonBody <| ioK8sApimachineryPkgApisMetaV1PatchEncoder model
    , expect = Http.expectJson ioK8sKubeAggregatorPkgApisApiregistrationV1beta1APIServiceDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   partially update status of the specified APIService
-}
patchApiregistrationV1beta1APIServiceStatus : String -> IoK8sApimachineryPkgApisMetaV1Patch -> Http.Request IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIService
patchApiregistrationV1beta1APIServiceStatus name model =
    { method = "PATCH"
    , url = basePath ++ "/apis/apiregistration.k8s.io/v1beta1/apiservices/" ++ name ++ "/status"
    , headers = []
    , body = Http.jsonBody <| ioK8sApimachineryPkgApisMetaV1PatchEncoder model
    , expect = Http.expectJson ioK8sKubeAggregatorPkgApisApiregistrationV1beta1APIServiceDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   read the specified APIService
-}
readApiregistrationV1beta1APIService : String -> Http.Request IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIService
readApiregistrationV1beta1APIService name =
    { method = "GET"
    , url = basePath ++ "/apis/apiregistration.k8s.io/v1beta1/apiservices/" ++ name
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson ioK8sKubeAggregatorPkgApisApiregistrationV1beta1APIServiceDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   read status of the specified APIService
-}
readApiregistrationV1beta1APIServiceStatus : String -> Http.Request IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIService
readApiregistrationV1beta1APIServiceStatus name =
    { method = "GET"
    , url = basePath ++ "/apis/apiregistration.k8s.io/v1beta1/apiservices/" ++ name ++ "/status"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson ioK8sKubeAggregatorPkgApisApiregistrationV1beta1APIServiceDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   replace the specified APIService
-}
replaceApiregistrationV1beta1APIService : String -> IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIService -> Http.Request IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIService
replaceApiregistrationV1beta1APIService name model =
    { method = "PUT"
    , url = basePath ++ "/apis/apiregistration.k8s.io/v1beta1/apiservices/" ++ name
    , headers = []
    , body = Http.jsonBody <| ioK8sKubeAggregatorPkgApisApiregistrationV1beta1APIServiceEncoder model
    , expect = Http.expectJson ioK8sKubeAggregatorPkgApisApiregistrationV1beta1APIServiceDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   replace status of the specified APIService
-}
replaceApiregistrationV1beta1APIServiceStatus : String -> IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIService -> Http.Request IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIService
replaceApiregistrationV1beta1APIServiceStatus name model =
    { method = "PUT"
    , url = basePath ++ "/apis/apiregistration.k8s.io/v1beta1/apiservices/" ++ name ++ "/status"
    , headers = []
    , body = Http.jsonBody <| ioK8sKubeAggregatorPkgApisApiregistrationV1beta1APIServiceEncoder model
    , expect = Http.expectJson ioK8sKubeAggregatorPkgApisApiregistrationV1beta1APIServiceDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   watch changes to an object of kind APIService. deprecated: use the &#39;watch&#39; parameter with a list operation instead, filtered to a single item with the &#39;fieldSelector&#39; parameter.
-}
watchApiregistrationV1beta1APIService : String -> Http.Request IoK8sApimachineryPkgApisMetaV1WatchEvent
watchApiregistrationV1beta1APIService name =
    { method = "GET"
    , url = basePath ++ "/apis/apiregistration.k8s.io/v1beta1/watch/apiservices/" ++ name
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson ioK8sApimachineryPkgApisMetaV1WatchEventDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   watch individual changes to a list of APIService. deprecated: use the &#39;watch&#39; parameter with a list operation instead.
-}
watchApiregistrationV1beta1APIServiceList : Http.Request IoK8sApimachineryPkgApisMetaV1WatchEvent
watchApiregistrationV1beta1APIServiceList =
    { method = "GET"
    , url = basePath ++ "/apis/apiregistration.k8s.io/v1beta1/watch/apiservices"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson ioK8sApimachineryPkgApisMetaV1WatchEventDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


