{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Request.AuthenticationV1beta1 exposing (createAuthenticationV1beta1TokenReview, getAuthenticationV1beta1APIResources)

import Data.IoK8sApimachineryPkgApisMetaV1APIResourceList exposing (IoK8sApimachineryPkgApisMetaV1APIResourceList, ioK8sApimachineryPkgApisMetaV1APIResourceListDecoder)
import Data.IoK8sApiAuthenticationV1beta1TokenReview exposing (IoK8sApiAuthenticationV1beta1TokenReview, ioK8sApiAuthenticationV1beta1TokenReviewDecoder, ioK8sApiAuthenticationV1beta1TokenReviewEncoder)
import Http
import Json.Decode as Decode


basePath : String
basePath =
    "https://localhost"


{-
   create a TokenReview
-}
createAuthenticationV1beta1TokenReview : IoK8sApiAuthenticationV1beta1TokenReview -> Http.Request IoK8sApiAuthenticationV1beta1TokenReview
createAuthenticationV1beta1TokenReview model =
    { method = "POST"
    , url = basePath ++ "/apis/authentication.k8s.io/v1beta1/tokenreviews"
    , headers = []
    , body = Http.jsonBody <| ioK8sApiAuthenticationV1beta1TokenReviewEncoder model
    , expect = Http.expectJson ioK8sApiAuthenticationV1beta1TokenReviewDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   get available resources
-}
getAuthenticationV1beta1APIResources : Http.Request IoK8sApimachineryPkgApisMetaV1APIResourceList
getAuthenticationV1beta1APIResources =
    { method = "GET"
    , url = basePath ++ "/apis/authentication.k8s.io/v1beta1/"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson ioK8sApimachineryPkgApisMetaV1APIResourceListDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


