{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Request.EventsV1beta1 exposing (createEventsV1beta1NamespacedEvent, deleteEventsV1beta1CollectionNamespacedEvent, deleteEventsV1beta1NamespacedEvent, getEventsV1beta1APIResources, listEventsV1beta1EventForAllNamespaces, listEventsV1beta1NamespacedEvent, patchEventsV1beta1NamespacedEvent, readEventsV1beta1NamespacedEvent, replaceEventsV1beta1NamespacedEvent, watchEventsV1beta1EventListForAllNamespaces, watchEventsV1beta1NamespacedEvent, watchEventsV1beta1NamespacedEventList)

import Data.IoK8sApiEventsV1beta1EventList exposing (IoK8sApiEventsV1beta1EventList, ioK8sApiEventsV1beta1EventListDecoder)
import Data.IoK8sApimachineryPkgApisMetaV1DeleteOptions exposing (IoK8sApimachineryPkgApisMetaV1DeleteOptions, ioK8sApimachineryPkgApisMetaV1DeleteOptionsEncoder)
import Data.IoK8sApiEventsV1beta1Event exposing (IoK8sApiEventsV1beta1Event, ioK8sApiEventsV1beta1EventDecoder, ioK8sApiEventsV1beta1EventEncoder)
import Data.IoK8sApimachineryPkgApisMetaV1Status exposing (IoK8sApimachineryPkgApisMetaV1Status, ioK8sApimachineryPkgApisMetaV1StatusDecoder)
import Data.IoK8sApimachineryPkgApisMetaV1APIResourceList exposing (IoK8sApimachineryPkgApisMetaV1APIResourceList, ioK8sApimachineryPkgApisMetaV1APIResourceListDecoder)
import Data.IoK8sApimachineryPkgApisMetaV1Patch exposing (IoK8sApimachineryPkgApisMetaV1Patch, ioK8sApimachineryPkgApisMetaV1PatchEncoder)
import Data.IoK8sApimachineryPkgApisMetaV1WatchEvent exposing (IoK8sApimachineryPkgApisMetaV1WatchEvent, ioK8sApimachineryPkgApisMetaV1WatchEventDecoder)
import Http
import Json.Decode as Decode


basePath : String
basePath =
    "https://localhost"


{-
   create an Event
-}
createEventsV1beta1NamespacedEvent : String -> IoK8sApiEventsV1beta1Event -> Http.Request IoK8sApiEventsV1beta1Event
createEventsV1beta1NamespacedEvent namespace model =
    { method = "POST"
    , url = basePath ++ "/apis/events.k8s.io/v1beta1/namespaces/" ++ namespace ++ "/events"
    , headers = []
    , body = Http.jsonBody <| ioK8sApiEventsV1beta1EventEncoder model
    , expect = Http.expectJson ioK8sApiEventsV1beta1EventDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   delete collection of Event
-}
deleteEventsV1beta1CollectionNamespacedEvent : String -> Http.Request IoK8sApimachineryPkgApisMetaV1Status
deleteEventsV1beta1CollectionNamespacedEvent namespace =
    { method = "DELETE"
    , url = basePath ++ "/apis/events.k8s.io/v1beta1/namespaces/" ++ namespace ++ "/events"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson ioK8sApimachineryPkgApisMetaV1StatusDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   delete an Event
-}
deleteEventsV1beta1NamespacedEvent : String -> String -> IoK8sApimachineryPkgApisMetaV1DeleteOptions -> Http.Request IoK8sApimachineryPkgApisMetaV1Status
deleteEventsV1beta1NamespacedEvent name namespace model =
    { method = "DELETE"
    , url = basePath ++ "/apis/events.k8s.io/v1beta1/namespaces/" ++ namespace ++ "/events/" ++ name
    , headers = []
    , body = Http.jsonBody <| ioK8sApimachineryPkgApisMetaV1DeleteOptionsEncoder model
    , expect = Http.expectJson ioK8sApimachineryPkgApisMetaV1StatusDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   get available resources
-}
getEventsV1beta1APIResources : Http.Request IoK8sApimachineryPkgApisMetaV1APIResourceList
getEventsV1beta1APIResources =
    { method = "GET"
    , url = basePath ++ "/apis/events.k8s.io/v1beta1/"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson ioK8sApimachineryPkgApisMetaV1APIResourceListDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   list or watch objects of kind Event
-}
listEventsV1beta1EventForAllNamespaces : Http.Request IoK8sApiEventsV1beta1EventList
listEventsV1beta1EventForAllNamespaces =
    { method = "GET"
    , url = basePath ++ "/apis/events.k8s.io/v1beta1/events"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson ioK8sApiEventsV1beta1EventListDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   list or watch objects of kind Event
-}
listEventsV1beta1NamespacedEvent : String -> Http.Request IoK8sApiEventsV1beta1EventList
listEventsV1beta1NamespacedEvent namespace =
    { method = "GET"
    , url = basePath ++ "/apis/events.k8s.io/v1beta1/namespaces/" ++ namespace ++ "/events"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson ioK8sApiEventsV1beta1EventListDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   partially update the specified Event
-}
patchEventsV1beta1NamespacedEvent : String -> String -> IoK8sApimachineryPkgApisMetaV1Patch -> Http.Request IoK8sApiEventsV1beta1Event
patchEventsV1beta1NamespacedEvent name namespace model =
    { method = "PATCH"
    , url = basePath ++ "/apis/events.k8s.io/v1beta1/namespaces/" ++ namespace ++ "/events/" ++ name
    , headers = []
    , body = Http.jsonBody <| ioK8sApimachineryPkgApisMetaV1PatchEncoder model
    , expect = Http.expectJson ioK8sApiEventsV1beta1EventDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   read the specified Event
-}
readEventsV1beta1NamespacedEvent : String -> String -> Http.Request IoK8sApiEventsV1beta1Event
readEventsV1beta1NamespacedEvent name namespace =
    { method = "GET"
    , url = basePath ++ "/apis/events.k8s.io/v1beta1/namespaces/" ++ namespace ++ "/events/" ++ name
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson ioK8sApiEventsV1beta1EventDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   replace the specified Event
-}
replaceEventsV1beta1NamespacedEvent : String -> String -> IoK8sApiEventsV1beta1Event -> Http.Request IoK8sApiEventsV1beta1Event
replaceEventsV1beta1NamespacedEvent name namespace model =
    { method = "PUT"
    , url = basePath ++ "/apis/events.k8s.io/v1beta1/namespaces/" ++ namespace ++ "/events/" ++ name
    , headers = []
    , body = Http.jsonBody <| ioK8sApiEventsV1beta1EventEncoder model
    , expect = Http.expectJson ioK8sApiEventsV1beta1EventDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   watch individual changes to a list of Event. deprecated: use the &#39;watch&#39; parameter with a list operation instead.
-}
watchEventsV1beta1EventListForAllNamespaces : Http.Request IoK8sApimachineryPkgApisMetaV1WatchEvent
watchEventsV1beta1EventListForAllNamespaces =
    { method = "GET"
    , url = basePath ++ "/apis/events.k8s.io/v1beta1/watch/events"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson ioK8sApimachineryPkgApisMetaV1WatchEventDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   watch changes to an object of kind Event. deprecated: use the &#39;watch&#39; parameter with a list operation instead, filtered to a single item with the &#39;fieldSelector&#39; parameter.
-}
watchEventsV1beta1NamespacedEvent : String -> String -> Http.Request IoK8sApimachineryPkgApisMetaV1WatchEvent
watchEventsV1beta1NamespacedEvent name namespace =
    { method = "GET"
    , url = basePath ++ "/apis/events.k8s.io/v1beta1/watch/namespaces/" ++ namespace ++ "/events/" ++ name
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson ioK8sApimachineryPkgApisMetaV1WatchEventDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   watch individual changes to a list of Event. deprecated: use the &#39;watch&#39; parameter with a list operation instead.
-}
watchEventsV1beta1NamespacedEventList : String -> Http.Request IoK8sApimachineryPkgApisMetaV1WatchEvent
watchEventsV1beta1NamespacedEventList namespace =
    { method = "GET"
    , url = basePath ++ "/apis/events.k8s.io/v1beta1/watch/namespaces/" ++ namespace ++ "/events"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson ioK8sApimachineryPkgApisMetaV1WatchEventDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


