{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Request.SettingsV1alpha1 exposing (createSettingsV1alpha1NamespacedPodPreset, deleteSettingsV1alpha1CollectionNamespacedPodPreset, deleteSettingsV1alpha1NamespacedPodPreset, getSettingsV1alpha1APIResources, listSettingsV1alpha1NamespacedPodPreset, listSettingsV1alpha1PodPresetForAllNamespaces, patchSettingsV1alpha1NamespacedPodPreset, readSettingsV1alpha1NamespacedPodPreset, replaceSettingsV1alpha1NamespacedPodPreset, watchSettingsV1alpha1NamespacedPodPreset, watchSettingsV1alpha1NamespacedPodPresetList, watchSettingsV1alpha1PodPresetListForAllNamespaces)

import Data.IoK8sApimachineryPkgApisMetaV1DeleteOptions exposing (IoK8sApimachineryPkgApisMetaV1DeleteOptions, ioK8sApimachineryPkgApisMetaV1DeleteOptionsEncoder)
import Data.IoK8sApimachineryPkgApisMetaV1Status exposing (IoK8sApimachineryPkgApisMetaV1Status, ioK8sApimachineryPkgApisMetaV1StatusDecoder)
import Data.IoK8sApimachineryPkgApisMetaV1APIResourceList exposing (IoK8sApimachineryPkgApisMetaV1APIResourceList, ioK8sApimachineryPkgApisMetaV1APIResourceListDecoder)
import Data.IoK8sApiSettingsV1alpha1PodPresetList exposing (IoK8sApiSettingsV1alpha1PodPresetList, ioK8sApiSettingsV1alpha1PodPresetListDecoder)
import Data.IoK8sApiSettingsV1alpha1PodPreset exposing (IoK8sApiSettingsV1alpha1PodPreset, ioK8sApiSettingsV1alpha1PodPresetDecoder, ioK8sApiSettingsV1alpha1PodPresetEncoder)
import Data.IoK8sApimachineryPkgApisMetaV1Patch exposing (IoK8sApimachineryPkgApisMetaV1Patch, ioK8sApimachineryPkgApisMetaV1PatchEncoder)
import Data.IoK8sApimachineryPkgApisMetaV1WatchEvent exposing (IoK8sApimachineryPkgApisMetaV1WatchEvent, ioK8sApimachineryPkgApisMetaV1WatchEventDecoder)
import Http
import Json.Decode as Decode


basePath : String
basePath =
    "https://localhost"


{-
   create a PodPreset
-}
createSettingsV1alpha1NamespacedPodPreset : String -> IoK8sApiSettingsV1alpha1PodPreset -> Http.Request IoK8sApiSettingsV1alpha1PodPreset
createSettingsV1alpha1NamespacedPodPreset namespace model =
    { method = "POST"
    , url = basePath ++ "/apis/settings.k8s.io/v1alpha1/namespaces/" ++ namespace ++ "/podpresets"
    , headers = []
    , body = Http.jsonBody <| ioK8sApiSettingsV1alpha1PodPresetEncoder model
    , expect = Http.expectJson ioK8sApiSettingsV1alpha1PodPresetDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   delete collection of PodPreset
-}
deleteSettingsV1alpha1CollectionNamespacedPodPreset : String -> Http.Request IoK8sApimachineryPkgApisMetaV1Status
deleteSettingsV1alpha1CollectionNamespacedPodPreset namespace =
    { method = "DELETE"
    , url = basePath ++ "/apis/settings.k8s.io/v1alpha1/namespaces/" ++ namespace ++ "/podpresets"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson ioK8sApimachineryPkgApisMetaV1StatusDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   delete a PodPreset
-}
deleteSettingsV1alpha1NamespacedPodPreset : String -> String -> IoK8sApimachineryPkgApisMetaV1DeleteOptions -> Http.Request IoK8sApimachineryPkgApisMetaV1Status
deleteSettingsV1alpha1NamespacedPodPreset name namespace model =
    { method = "DELETE"
    , url = basePath ++ "/apis/settings.k8s.io/v1alpha1/namespaces/" ++ namespace ++ "/podpresets/" ++ name
    , headers = []
    , body = Http.jsonBody <| ioK8sApimachineryPkgApisMetaV1DeleteOptionsEncoder model
    , expect = Http.expectJson ioK8sApimachineryPkgApisMetaV1StatusDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   get available resources
-}
getSettingsV1alpha1APIResources : Http.Request IoK8sApimachineryPkgApisMetaV1APIResourceList
getSettingsV1alpha1APIResources =
    { method = "GET"
    , url = basePath ++ "/apis/settings.k8s.io/v1alpha1/"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson ioK8sApimachineryPkgApisMetaV1APIResourceListDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   list or watch objects of kind PodPreset
-}
listSettingsV1alpha1NamespacedPodPreset : String -> Http.Request IoK8sApiSettingsV1alpha1PodPresetList
listSettingsV1alpha1NamespacedPodPreset namespace =
    { method = "GET"
    , url = basePath ++ "/apis/settings.k8s.io/v1alpha1/namespaces/" ++ namespace ++ "/podpresets"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson ioK8sApiSettingsV1alpha1PodPresetListDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   list or watch objects of kind PodPreset
-}
listSettingsV1alpha1PodPresetForAllNamespaces : Http.Request IoK8sApiSettingsV1alpha1PodPresetList
listSettingsV1alpha1PodPresetForAllNamespaces =
    { method = "GET"
    , url = basePath ++ "/apis/settings.k8s.io/v1alpha1/podpresets"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson ioK8sApiSettingsV1alpha1PodPresetListDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   partially update the specified PodPreset
-}
patchSettingsV1alpha1NamespacedPodPreset : String -> String -> IoK8sApimachineryPkgApisMetaV1Patch -> Http.Request IoK8sApiSettingsV1alpha1PodPreset
patchSettingsV1alpha1NamespacedPodPreset name namespace model =
    { method = "PATCH"
    , url = basePath ++ "/apis/settings.k8s.io/v1alpha1/namespaces/" ++ namespace ++ "/podpresets/" ++ name
    , headers = []
    , body = Http.jsonBody <| ioK8sApimachineryPkgApisMetaV1PatchEncoder model
    , expect = Http.expectJson ioK8sApiSettingsV1alpha1PodPresetDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   read the specified PodPreset
-}
readSettingsV1alpha1NamespacedPodPreset : String -> String -> Http.Request IoK8sApiSettingsV1alpha1PodPreset
readSettingsV1alpha1NamespacedPodPreset name namespace =
    { method = "GET"
    , url = basePath ++ "/apis/settings.k8s.io/v1alpha1/namespaces/" ++ namespace ++ "/podpresets/" ++ name
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson ioK8sApiSettingsV1alpha1PodPresetDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   replace the specified PodPreset
-}
replaceSettingsV1alpha1NamespacedPodPreset : String -> String -> IoK8sApiSettingsV1alpha1PodPreset -> Http.Request IoK8sApiSettingsV1alpha1PodPreset
replaceSettingsV1alpha1NamespacedPodPreset name namespace model =
    { method = "PUT"
    , url = basePath ++ "/apis/settings.k8s.io/v1alpha1/namespaces/" ++ namespace ++ "/podpresets/" ++ name
    , headers = []
    , body = Http.jsonBody <| ioK8sApiSettingsV1alpha1PodPresetEncoder model
    , expect = Http.expectJson ioK8sApiSettingsV1alpha1PodPresetDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   watch changes to an object of kind PodPreset. deprecated: use the &#39;watch&#39; parameter with a list operation instead, filtered to a single item with the &#39;fieldSelector&#39; parameter.
-}
watchSettingsV1alpha1NamespacedPodPreset : String -> String -> Http.Request IoK8sApimachineryPkgApisMetaV1WatchEvent
watchSettingsV1alpha1NamespacedPodPreset name namespace =
    { method = "GET"
    , url = basePath ++ "/apis/settings.k8s.io/v1alpha1/watch/namespaces/" ++ namespace ++ "/podpresets/" ++ name
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson ioK8sApimachineryPkgApisMetaV1WatchEventDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   watch individual changes to a list of PodPreset. deprecated: use the &#39;watch&#39; parameter with a list operation instead.
-}
watchSettingsV1alpha1NamespacedPodPresetList : String -> Http.Request IoK8sApimachineryPkgApisMetaV1WatchEvent
watchSettingsV1alpha1NamespacedPodPresetList namespace =
    { method = "GET"
    , url = basePath ++ "/apis/settings.k8s.io/v1alpha1/watch/namespaces/" ++ namespace ++ "/podpresets"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson ioK8sApimachineryPkgApisMetaV1WatchEventDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   watch individual changes to a list of PodPreset. deprecated: use the &#39;watch&#39; parameter with a list operation instead.
-}
watchSettingsV1alpha1PodPresetListForAllNamespaces : Http.Request IoK8sApimachineryPkgApisMetaV1WatchEvent
watchSettingsV1alpha1PodPresetListForAllNamespaces =
    { method = "GET"
    , url = basePath ++ "/apis/settings.k8s.io/v1alpha1/watch/podpresets"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson ioK8sApimachineryPkgApisMetaV1WatchEventDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


