{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Request.StorageV1alpha1 exposing (createStorageV1alpha1VolumeAttachment, deleteStorageV1alpha1CollectionVolumeAttachment, deleteStorageV1alpha1VolumeAttachment, getStorageV1alpha1APIResources, listStorageV1alpha1VolumeAttachment, patchStorageV1alpha1VolumeAttachment, readStorageV1alpha1VolumeAttachment, replaceStorageV1alpha1VolumeAttachment, watchStorageV1alpha1VolumeAttachment, watchStorageV1alpha1VolumeAttachmentList)

import Data.IoK8sApimachineryPkgApisMetaV1DeleteOptions exposing (IoK8sApimachineryPkgApisMetaV1DeleteOptions, ioK8sApimachineryPkgApisMetaV1DeleteOptionsEncoder)
import Data.IoK8sApiStorageV1alpha1VolumeAttachment exposing (IoK8sApiStorageV1alpha1VolumeAttachment, ioK8sApiStorageV1alpha1VolumeAttachmentDecoder, ioK8sApiStorageV1alpha1VolumeAttachmentEncoder)
import Data.IoK8sApimachineryPkgApisMetaV1Status exposing (IoK8sApimachineryPkgApisMetaV1Status, ioK8sApimachineryPkgApisMetaV1StatusDecoder)
import Data.IoK8sApimachineryPkgApisMetaV1APIResourceList exposing (IoK8sApimachineryPkgApisMetaV1APIResourceList, ioK8sApimachineryPkgApisMetaV1APIResourceListDecoder)
import Data.IoK8sApiStorageV1alpha1VolumeAttachmentList exposing (IoK8sApiStorageV1alpha1VolumeAttachmentList, ioK8sApiStorageV1alpha1VolumeAttachmentListDecoder)
import Data.IoK8sApimachineryPkgApisMetaV1Patch exposing (IoK8sApimachineryPkgApisMetaV1Patch, ioK8sApimachineryPkgApisMetaV1PatchEncoder)
import Data.IoK8sApimachineryPkgApisMetaV1WatchEvent exposing (IoK8sApimachineryPkgApisMetaV1WatchEvent, ioK8sApimachineryPkgApisMetaV1WatchEventDecoder)
import Http
import Json.Decode as Decode


basePath : String
basePath =
    "https://localhost"


{-
   create a VolumeAttachment
-}
createStorageV1alpha1VolumeAttachment : IoK8sApiStorageV1alpha1VolumeAttachment -> Http.Request IoK8sApiStorageV1alpha1VolumeAttachment
createStorageV1alpha1VolumeAttachment model =
    { method = "POST"
    , url = basePath ++ "/apis/storage.k8s.io/v1alpha1/volumeattachments"
    , headers = []
    , body = Http.jsonBody <| ioK8sApiStorageV1alpha1VolumeAttachmentEncoder model
    , expect = Http.expectJson ioK8sApiStorageV1alpha1VolumeAttachmentDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   delete collection of VolumeAttachment
-}
deleteStorageV1alpha1CollectionVolumeAttachment : Http.Request IoK8sApimachineryPkgApisMetaV1Status
deleteStorageV1alpha1CollectionVolumeAttachment =
    { method = "DELETE"
    , url = basePath ++ "/apis/storage.k8s.io/v1alpha1/volumeattachments"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson ioK8sApimachineryPkgApisMetaV1StatusDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   delete a VolumeAttachment
-}
deleteStorageV1alpha1VolumeAttachment : String -> IoK8sApimachineryPkgApisMetaV1DeleteOptions -> Http.Request IoK8sApimachineryPkgApisMetaV1Status
deleteStorageV1alpha1VolumeAttachment name model =
    { method = "DELETE"
    , url = basePath ++ "/apis/storage.k8s.io/v1alpha1/volumeattachments/" ++ name
    , headers = []
    , body = Http.jsonBody <| ioK8sApimachineryPkgApisMetaV1DeleteOptionsEncoder model
    , expect = Http.expectJson ioK8sApimachineryPkgApisMetaV1StatusDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   get available resources
-}
getStorageV1alpha1APIResources : Http.Request IoK8sApimachineryPkgApisMetaV1APIResourceList
getStorageV1alpha1APIResources =
    { method = "GET"
    , url = basePath ++ "/apis/storage.k8s.io/v1alpha1/"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson ioK8sApimachineryPkgApisMetaV1APIResourceListDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   list or watch objects of kind VolumeAttachment
-}
listStorageV1alpha1VolumeAttachment : Http.Request IoK8sApiStorageV1alpha1VolumeAttachmentList
listStorageV1alpha1VolumeAttachment =
    { method = "GET"
    , url = basePath ++ "/apis/storage.k8s.io/v1alpha1/volumeattachments"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson ioK8sApiStorageV1alpha1VolumeAttachmentListDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   partially update the specified VolumeAttachment
-}
patchStorageV1alpha1VolumeAttachment : String -> IoK8sApimachineryPkgApisMetaV1Patch -> Http.Request IoK8sApiStorageV1alpha1VolumeAttachment
patchStorageV1alpha1VolumeAttachment name model =
    { method = "PATCH"
    , url = basePath ++ "/apis/storage.k8s.io/v1alpha1/volumeattachments/" ++ name
    , headers = []
    , body = Http.jsonBody <| ioK8sApimachineryPkgApisMetaV1PatchEncoder model
    , expect = Http.expectJson ioK8sApiStorageV1alpha1VolumeAttachmentDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   read the specified VolumeAttachment
-}
readStorageV1alpha1VolumeAttachment : String -> Http.Request IoK8sApiStorageV1alpha1VolumeAttachment
readStorageV1alpha1VolumeAttachment name =
    { method = "GET"
    , url = basePath ++ "/apis/storage.k8s.io/v1alpha1/volumeattachments/" ++ name
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson ioK8sApiStorageV1alpha1VolumeAttachmentDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   replace the specified VolumeAttachment
-}
replaceStorageV1alpha1VolumeAttachment : String -> IoK8sApiStorageV1alpha1VolumeAttachment -> Http.Request IoK8sApiStorageV1alpha1VolumeAttachment
replaceStorageV1alpha1VolumeAttachment name model =
    { method = "PUT"
    , url = basePath ++ "/apis/storage.k8s.io/v1alpha1/volumeattachments/" ++ name
    , headers = []
    , body = Http.jsonBody <| ioK8sApiStorageV1alpha1VolumeAttachmentEncoder model
    , expect = Http.expectJson ioK8sApiStorageV1alpha1VolumeAttachmentDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   watch changes to an object of kind VolumeAttachment. deprecated: use the &#39;watch&#39; parameter with a list operation instead, filtered to a single item with the &#39;fieldSelector&#39; parameter.
-}
watchStorageV1alpha1VolumeAttachment : String -> Http.Request IoK8sApimachineryPkgApisMetaV1WatchEvent
watchStorageV1alpha1VolumeAttachment name =
    { method = "GET"
    , url = basePath ++ "/apis/storage.k8s.io/v1alpha1/watch/volumeattachments/" ++ name
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson ioK8sApimachineryPkgApisMetaV1WatchEventDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   watch individual changes to a list of VolumeAttachment. deprecated: use the &#39;watch&#39; parameter with a list operation instead.
-}
watchStorageV1alpha1VolumeAttachmentList : Http.Request IoK8sApimachineryPkgApisMetaV1WatchEvent
watchStorageV1alpha1VolumeAttachmentList =
    { method = "GET"
    , url = basePath ++ "/apis/storage.k8s.io/v1alpha1/watch/volumeattachments"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson ioK8sApimachineryPkgApisMetaV1WatchEventDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


