{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Request.Version exposing (getCodeVersion)

import Data.IoK8sApimachineryPkgVersionInfo exposing (IoK8sApimachineryPkgVersionInfo, ioK8sApimachineryPkgVersionInfoDecoder)
import Http
import Json.Decode as Decode


basePath : String
basePath =
    "https://localhost"


{-
   get the code version
-}
getCodeVersion : Http.Request IoK8sApimachineryPkgVersionInfo
getCodeVersion =
    { method = "GET"
    , url = basePath ++ "/version/"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson ioK8sApimachineryPkgVersionInfoDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


