{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sKubernetesPkgApiV1Probe exposing (IoK8sKubernetesPkgApiV1Probe, ioK8sKubernetesPkgApiV1ProbeDecoder, ioK8sKubernetesPkgApiV1ProbeEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)




type alias IoK8sKubernetesPkgApiV1Probe =
    {     }


ioK8sKubernetesPkgApiV1ProbeDecoder : Decoder IoK8sKubernetesPkgApiV1Probe
ioK8sKubernetesPkgApiV1ProbeDecoder =
    decode IoK8sKubernetesPkgApiV1Probe



ioK8sKubernetesPkgApiV1ProbeEncoder : IoK8sKubernetesPkgApiV1Probe -> Encode.Value
ioK8sKubernetesPkgApiV1ProbeEncoder model =
    Encode.object
        ]


