{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiCoreV1EventList exposing (IoK8sApiCoreV1EventList, ioK8sApiCoreV1EventListDecoder, ioK8sApiCoreV1EventListEncoder)

import Data.IoK8sApiCoreV1Event exposing (IoK8sApiCoreV1Event, ioK8sApiCoreV1EventDecoder, ioK8sApiCoreV1EventEncoder)
import Data.IoK8sApimachineryPkgApisMetaV1ListMeta exposing (IoK8sApimachineryPkgApisMetaV1ListMeta, ioK8sApimachineryPkgApisMetaV1ListMetaDecoder, ioK8sApimachineryPkgApisMetaV1ListMetaEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   EventList is a list of events.
-}


type alias IoK8sApiCoreV1EventList =
    { apiVersion : Maybe String
    , items : (List IoK8sApiCoreV1Event)
    , kind : Maybe String
    , metadata : Maybe IoK8sApimachineryPkgApisMetaV1ListMeta
    }


ioK8sApiCoreV1EventListDecoder : Decoder IoK8sApiCoreV1EventList
ioK8sApiCoreV1EventListDecoder =
    decode IoK8sApiCoreV1EventList
        |> optional "apiVersion" (Decode.nullable Decode.string) Nothing
        |> required "items" (Decode.list ioK8sApiCoreV1EventDecoder)
        |> optional "kind" (Decode.nullable Decode.string) Nothing
        |> optional "metadata" (Decode.nullable ioK8sApimachineryPkgApisMetaV1ListMetaDecoder) Nothing



ioK8sApiCoreV1EventListEncoder : IoK8sApiCoreV1EventList -> Encode.Value
ioK8sApiCoreV1EventListEncoder model =
    Encode.object
        [ ( "apiVersion", withDefault Encode.null (map Encode.string model.apiVersion) )
        , ( "items", (Encode.list << List.map ioK8sApiCoreV1EventEncoder) model.items )
        , ( "kind", withDefault Encode.null (map Encode.string model.kind) )
        , ( "metadata", withDefault Encode.null (map ioK8sApimachineryPkgApisMetaV1ListMetaEncoder model.metadata) )
        ]


