{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiRbacV1RoleRef exposing (IoK8sApiRbacV1RoleRef, ioK8sApiRbacV1RoleRefDecoder, ioK8sApiRbacV1RoleRefEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   RoleRef contains information that points to the role being used
-}


type alias IoK8sApiRbacV1RoleRef =
    { apiGroup : String
    , kind : String
    , name : String
    }


ioK8sApiRbacV1RoleRefDecoder : Decoder IoK8sApiRbacV1RoleRef
ioK8sApiRbacV1RoleRefDecoder =
    decode IoK8sApiRbacV1RoleRef
        |> required "apiGroup" Decode.string
        |> required "kind" Decode.string
        |> required "name" Decode.string



ioK8sApiRbacV1RoleRefEncoder : IoK8sApiRbacV1RoleRef -> Encode.Value
ioK8sApiRbacV1RoleRefEncoder model =
    Encode.object
        [ ( "apiGroup", Encode.string model.apiGroup )
        , ( "kind", Encode.string model.kind )
        , ( "name", Encode.string model.name )
        ]


