{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiAppsV1beta2ScaleSpec exposing (IoK8sApiAppsV1beta2ScaleSpec, ioK8sApiAppsV1beta2ScaleSpecDecoder, ioK8sApiAppsV1beta2ScaleSpecEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   ScaleSpec describes the attributes of a scale subresource
-}


type alias IoK8sApiAppsV1beta2ScaleSpec =
    { replicas : Maybe Int
    }


ioK8sApiAppsV1beta2ScaleSpecDecoder : Decoder IoK8sApiAppsV1beta2ScaleSpec
ioK8sApiAppsV1beta2ScaleSpecDecoder =
    decode IoK8sApiAppsV1beta2ScaleSpec
        |> optional "replicas" (Decode.nullable Decode.int) Nothing



ioK8sApiAppsV1beta2ScaleSpecEncoder : IoK8sApiAppsV1beta2ScaleSpec -> Encode.Value
ioK8sApiAppsV1beta2ScaleSpecEncoder model =
    Encode.object
        [ ( "replicas", withDefault Encode.null (map Encode.int model.replicas) )
        ]


