{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiAdmissionregistrationV1beta1ValidatingWebhookConfigurationList exposing (IoK8sApiAdmissionregistrationV1beta1ValidatingWebhookConfigurationList, ioK8sApiAdmissionregistrationV1beta1ValidatingWebhookConfigurationListDecoder, ioK8sApiAdmissionregistrationV1beta1ValidatingWebhookConfigurationListEncoder)

import Data.IoK8sApiAdmissionregistrationV1beta1ValidatingWebhookConfiguration exposing (IoK8sApiAdmissionregistrationV1beta1ValidatingWebhookConfiguration, ioK8sApiAdmissionregistrationV1beta1ValidatingWebhookConfigurationDecoder, ioK8sApiAdmissionregistrationV1beta1ValidatingWebhookConfigurationEncoder)
import Data.IoK8sApimachineryPkgApisMetaV1ListMeta exposing (IoK8sApimachineryPkgApisMetaV1ListMeta, ioK8sApimachineryPkgApisMetaV1ListMetaDecoder, ioK8sApimachineryPkgApisMetaV1ListMetaEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   ValidatingWebhookConfigurationList is a list of ValidatingWebhookConfiguration.
-}


type alias IoK8sApiAdmissionregistrationV1beta1ValidatingWebhookConfigurationList =
    { apiVersion : Maybe String
    , items : (List IoK8sApiAdmissionregistrationV1beta1ValidatingWebhookConfiguration)
    , kind : Maybe String
    , metadata : Maybe IoK8sApimachineryPkgApisMetaV1ListMeta
    }


ioK8sApiAdmissionregistrationV1beta1ValidatingWebhookConfigurationListDecoder : Decoder IoK8sApiAdmissionregistrationV1beta1ValidatingWebhookConfigurationList
ioK8sApiAdmissionregistrationV1beta1ValidatingWebhookConfigurationListDecoder =
    decode IoK8sApiAdmissionregistrationV1beta1ValidatingWebhookConfigurationList
        |> optional "apiVersion" (Decode.nullable Decode.string) Nothing
        |> required "items" (Decode.list ioK8sApiAdmissionregistrationV1beta1ValidatingWebhookConfigurationDecoder)
        |> optional "kind" (Decode.nullable Decode.string) Nothing
        |> optional "metadata" (Decode.nullable ioK8sApimachineryPkgApisMetaV1ListMetaDecoder) Nothing



ioK8sApiAdmissionregistrationV1beta1ValidatingWebhookConfigurationListEncoder : IoK8sApiAdmissionregistrationV1beta1ValidatingWebhookConfigurationList -> Encode.Value
ioK8sApiAdmissionregistrationV1beta1ValidatingWebhookConfigurationListEncoder model =
    Encode.object
        [ ( "apiVersion", withDefault Encode.null (map Encode.string model.apiVersion) )
        , ( "items", (Encode.list << List.map ioK8sApiAdmissionregistrationV1beta1ValidatingWebhookConfigurationEncoder) model.items )
        , ( "kind", withDefault Encode.null (map Encode.string model.kind) )
        , ( "metadata", withDefault Encode.null (map ioK8sApimachineryPkgApisMetaV1ListMetaEncoder model.metadata) )
        ]


