{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiAuthorizationV1NonResourceAttributes exposing (IoK8sApiAuthorizationV1NonResourceAttributes, ioK8sApiAuthorizationV1NonResourceAttributesDecoder, ioK8sApiAuthorizationV1NonResourceAttributesEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   NonResourceAttributes includes the authorization attributes available for non-resource requests to the Authorizer interface
-}


type alias IoK8sApiAuthorizationV1NonResourceAttributes =
    { path : Maybe String
    , verb : Maybe String
    }


ioK8sApiAuthorizationV1NonResourceAttributesDecoder : Decoder IoK8sApiAuthorizationV1NonResourceAttributes
ioK8sApiAuthorizationV1NonResourceAttributesDecoder =
    decode IoK8sApiAuthorizationV1NonResourceAttributes
        |> optional "path" (Decode.nullable Decode.string) Nothing
        |> optional "verb" (Decode.nullable Decode.string) Nothing



ioK8sApiAuthorizationV1NonResourceAttributesEncoder : IoK8sApiAuthorizationV1NonResourceAttributes -> Encode.Value
ioK8sApiAuthorizationV1NonResourceAttributesEncoder model =
    Encode.object
        [ ( "path", withDefault Encode.null (map Encode.string model.path) )
        , ( "verb", withDefault Encode.null (map Encode.string model.verb) )
        ]


