{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiNetworkingV1IPBlock exposing (IoK8sApiNetworkingV1IPBlock, ioK8sApiNetworkingV1IPBlockDecoder, ioK8sApiNetworkingV1IPBlockEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   IPBlock describes a particular CIDR (Ex. \"192.168.1.1/24\") that is allowed to the pods matched by a NetworkPolicySpec's podSelector. The except entry describes CIDRs that should not be included within this rule.
-}


type alias IoK8sApiNetworkingV1IPBlock =
    { cidr : String
    , except : Maybe (List String)
    }


ioK8sApiNetworkingV1IPBlockDecoder : Decoder IoK8sApiNetworkingV1IPBlock
ioK8sApiNetworkingV1IPBlockDecoder =
    decode IoK8sApiNetworkingV1IPBlock
        |> required "cidr" Decode.string
        |> optional "except" (Decode.nullable (Decode.list Decode.string)) Nothing



ioK8sApiNetworkingV1IPBlockEncoder : IoK8sApiNetworkingV1IPBlock -> Encode.Value
ioK8sApiNetworkingV1IPBlockEncoder model =
    Encode.object
        [ ( "cidr", Encode.string model.cidr )
        , ( "except", withDefault Encode.null (map (Encode.list << List.map Encode.string) model.except) )
        ]


