{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiExtensionsV1beta1NetworkPolicyEgressRule exposing (IoK8sApiExtensionsV1beta1NetworkPolicyEgressRule, ioK8sApiExtensionsV1beta1NetworkPolicyEgressRuleDecoder, ioK8sApiExtensionsV1beta1NetworkPolicyEgressRuleEncoder)

import Data.IoK8sApiExtensionsV1beta1NetworkPolicyPort exposing (IoK8sApiExtensionsV1beta1NetworkPolicyPort, ioK8sApiExtensionsV1beta1NetworkPolicyPortDecoder, ioK8sApiExtensionsV1beta1NetworkPolicyPortEncoder)
import Data.IoK8sApiExtensionsV1beta1NetworkPolicyPeer exposing (IoK8sApiExtensionsV1beta1NetworkPolicyPeer, ioK8sApiExtensionsV1beta1NetworkPolicyPeerDecoder, ioK8sApiExtensionsV1beta1NetworkPolicyPeerEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   DEPRECATED 1.9 - This group version of NetworkPolicyEgressRule is deprecated by networking/v1/NetworkPolicyEgressRule. NetworkPolicyEgressRule describes a particular set of traffic that is allowed out of pods matched by a NetworkPolicySpec's podSelector. The traffic must match both ports and to. This type is beta-level in 1.8
-}


type alias IoK8sApiExtensionsV1beta1NetworkPolicyEgressRule =
    { ports : Maybe (List IoK8sApiExtensionsV1beta1NetworkPolicyPort)
    , to : Maybe (List IoK8sApiExtensionsV1beta1NetworkPolicyPeer)
    }


ioK8sApiExtensionsV1beta1NetworkPolicyEgressRuleDecoder : Decoder IoK8sApiExtensionsV1beta1NetworkPolicyEgressRule
ioK8sApiExtensionsV1beta1NetworkPolicyEgressRuleDecoder =
    decode IoK8sApiExtensionsV1beta1NetworkPolicyEgressRule
        |> optional "ports" (Decode.nullable (Decode.list ioK8sApiExtensionsV1beta1NetworkPolicyPortDecoder)) Nothing
        |> optional "to" (Decode.nullable (Decode.list ioK8sApiExtensionsV1beta1NetworkPolicyPeerDecoder)) Nothing



ioK8sApiExtensionsV1beta1NetworkPolicyEgressRuleEncoder : IoK8sApiExtensionsV1beta1NetworkPolicyEgressRule -> Encode.Value
ioK8sApiExtensionsV1beta1NetworkPolicyEgressRuleEncoder model =
    Encode.object
        [ ( "ports", withDefault Encode.null (map (Encode.list << List.map ioK8sApiExtensionsV1beta1NetworkPolicyPortEncoder) model.ports) )
        , ( "to", withDefault Encode.null (map (Encode.list << List.map ioK8sApiExtensionsV1beta1NetworkPolicyPeerEncoder) model.to) )
        ]


