{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiStorageV1VolumeAttachmentSpec exposing (IoK8sApiStorageV1VolumeAttachmentSpec, ioK8sApiStorageV1VolumeAttachmentSpecDecoder, ioK8sApiStorageV1VolumeAttachmentSpecEncoder)

import Data.IoK8sApiStorageV1VolumeAttachmentSource exposing (IoK8sApiStorageV1VolumeAttachmentSource, ioK8sApiStorageV1VolumeAttachmentSourceDecoder, ioK8sApiStorageV1VolumeAttachmentSourceEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   VolumeAttachmentSpec is the specification of a VolumeAttachment request.
-}


type alias IoK8sApiStorageV1VolumeAttachmentSpec =
    { attacher : String
    , nodeName : String
    , source : IoK8sApiStorageV1VolumeAttachmentSource
    }


ioK8sApiStorageV1VolumeAttachmentSpecDecoder : Decoder IoK8sApiStorageV1VolumeAttachmentSpec
ioK8sApiStorageV1VolumeAttachmentSpecDecoder =
    decode IoK8sApiStorageV1VolumeAttachmentSpec
        |> required "attacher" Decode.string
        |> required "nodeName" Decode.string
        |> required "source" ioK8sApiStorageV1VolumeAttachmentSourceDecoder



ioK8sApiStorageV1VolumeAttachmentSpecEncoder : IoK8sApiStorageV1VolumeAttachmentSpec -> Encode.Value
ioK8sApiStorageV1VolumeAttachmentSpecEncoder model =
    Encode.object
        [ ( "attacher", Encode.string model.attacher )
        , ( "nodeName", Encode.string model.nodeName )
        , ( "source", ioK8sApiStorageV1VolumeAttachmentSourceEncoder model.source )
        ]


