{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiAutoscalingV2beta2ExternalMetricSource exposing (IoK8sApiAutoscalingV2beta2ExternalMetricSource, ioK8sApiAutoscalingV2beta2ExternalMetricSourceDecoder, ioK8sApiAutoscalingV2beta2ExternalMetricSourceEncoder)

import Data.IoK8sApiAutoscalingV2beta2MetricIdentifier exposing (IoK8sApiAutoscalingV2beta2MetricIdentifier, ioK8sApiAutoscalingV2beta2MetricIdentifierDecoder, ioK8sApiAutoscalingV2beta2MetricIdentifierEncoder)
import Data.IoK8sApiAutoscalingV2beta2MetricTarget exposing (IoK8sApiAutoscalingV2beta2MetricTarget, ioK8sApiAutoscalingV2beta2MetricTargetDecoder, ioK8sApiAutoscalingV2beta2MetricTargetEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   ExternalMetricSource indicates how to scale on a metric not associated with any Kubernetes object (for example length of queue in cloud messaging service, or QPS from loadbalancer running outside of cluster).
-}


type alias IoK8sApiAutoscalingV2beta2ExternalMetricSource =
    { metric : IoK8sApiAutoscalingV2beta2MetricIdentifier
    , target : IoK8sApiAutoscalingV2beta2MetricTarget
    }


ioK8sApiAutoscalingV2beta2ExternalMetricSourceDecoder : Decoder IoK8sApiAutoscalingV2beta2ExternalMetricSource
ioK8sApiAutoscalingV2beta2ExternalMetricSourceDecoder =
    decode IoK8sApiAutoscalingV2beta2ExternalMetricSource
        |> required "metric" ioK8sApiAutoscalingV2beta2MetricIdentifierDecoder
        |> required "target" ioK8sApiAutoscalingV2beta2MetricTargetDecoder



ioK8sApiAutoscalingV2beta2ExternalMetricSourceEncoder : IoK8sApiAutoscalingV2beta2ExternalMetricSource -> Encode.Value
ioK8sApiAutoscalingV2beta2ExternalMetricSourceEncoder model =
    Encode.object
        [ ( "metric", ioK8sApiAutoscalingV2beta2MetricIdentifierEncoder model.metric )
        , ( "target", ioK8sApiAutoscalingV2beta2MetricTargetEncoder model.target )
        ]


