{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiPolicyV1beta1IDRange exposing (IoK8sApiPolicyV1beta1IDRange, ioK8sApiPolicyV1beta1IDRangeDecoder, ioK8sApiPolicyV1beta1IDRangeEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   IDRange provides a min/max of an allowed range of IDs.
-}


type alias IoK8sApiPolicyV1beta1IDRange =
    { max : Int
    , min : Int
    }


ioK8sApiPolicyV1beta1IDRangeDecoder : Decoder IoK8sApiPolicyV1beta1IDRange
ioK8sApiPolicyV1beta1IDRangeDecoder =
    decode IoK8sApiPolicyV1beta1IDRange
        |> required "max" Decode.int
        |> required "min" Decode.int



ioK8sApiPolicyV1beta1IDRangeEncoder : IoK8sApiPolicyV1beta1IDRange -> Encode.Value
ioK8sApiPolicyV1beta1IDRangeEncoder model =
    Encode.object
        [ ( "max", Encode.int model.max )
        , ( "min", Encode.int model.min )
        ]


