{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiCoreV1HostPathVolumeSource exposing (IoK8sApiCoreV1HostPathVolumeSource, ioK8sApiCoreV1HostPathVolumeSourceDecoder, ioK8sApiCoreV1HostPathVolumeSourceEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   Represents a host path mapped into a pod. Host path volumes do not support ownership management or SELinux relabeling.
-}


type alias IoK8sApiCoreV1HostPathVolumeSource =
    { path : String
    , type_ : Maybe String
    }


ioK8sApiCoreV1HostPathVolumeSourceDecoder : Decoder IoK8sApiCoreV1HostPathVolumeSource
ioK8sApiCoreV1HostPathVolumeSourceDecoder =
    decode IoK8sApiCoreV1HostPathVolumeSource
        |> required "path" Decode.string
        |> optional "type" (Decode.nullable Decode.string) Nothing



ioK8sApiCoreV1HostPathVolumeSourceEncoder : IoK8sApiCoreV1HostPathVolumeSource -> Encode.Value
ioK8sApiCoreV1HostPathVolumeSourceEncoder model =
    Encode.object
        [ ( "path", Encode.string model.path )
        , ( "type", withDefault Encode.null (map Encode.string model.type_) )
        ]


