{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiCoreV1DaemonEndpoint exposing (IoK8sApiCoreV1DaemonEndpoint, ioK8sApiCoreV1DaemonEndpointDecoder, ioK8sApiCoreV1DaemonEndpointEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   DaemonEndpoint contains information about a single Daemon endpoint.
-}


type alias IoK8sApiCoreV1DaemonEndpoint =
    { Port_ : Int
    }


ioK8sApiCoreV1DaemonEndpointDecoder : Decoder IoK8sApiCoreV1DaemonEndpoint
ioK8sApiCoreV1DaemonEndpointDecoder =
    decode IoK8sApiCoreV1DaemonEndpoint
        |> required "Port" Decode.int



ioK8sApiCoreV1DaemonEndpointEncoder : IoK8sApiCoreV1DaemonEndpoint -> Encode.Value
ioK8sApiCoreV1DaemonEndpointEncoder model =
    Encode.object
        [ ( "Port", Encode.int model.Port_ )
        ]


