{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiNetworkingV1NetworkPolicyPeer exposing (IoK8sApiNetworkingV1NetworkPolicyPeer, ioK8sApiNetworkingV1NetworkPolicyPeerDecoder, ioK8sApiNetworkingV1NetworkPolicyPeerEncoder)

import Data.IoK8sApiNetworkingV1IPBlock exposing (IoK8sApiNetworkingV1IPBlock, ioK8sApiNetworkingV1IPBlockDecoder, ioK8sApiNetworkingV1IPBlockEncoder)
import Data.IoK8sApimachineryPkgApisMetaV1LabelSelector exposing (IoK8sApimachineryPkgApisMetaV1LabelSelector, ioK8sApimachineryPkgApisMetaV1LabelSelectorDecoder, ioK8sApimachineryPkgApisMetaV1LabelSelectorEncoder)
import Data.IoK8sApimachineryPkgApisMetaV1LabelSelector exposing (IoK8sApimachineryPkgApisMetaV1LabelSelector, ioK8sApimachineryPkgApisMetaV1LabelSelectorDecoder, ioK8sApimachineryPkgApisMetaV1LabelSelectorEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   NetworkPolicyPeer describes a peer to allow traffic from. Only certain combinations of fields are allowed
-}


type alias IoK8sApiNetworkingV1NetworkPolicyPeer =
    { ipBlock : Maybe IoK8sApiNetworkingV1IPBlock
    , namespaceSelector : Maybe IoK8sApimachineryPkgApisMetaV1LabelSelector
    , podSelector : Maybe IoK8sApimachineryPkgApisMetaV1LabelSelector
    }


ioK8sApiNetworkingV1NetworkPolicyPeerDecoder : Decoder IoK8sApiNetworkingV1NetworkPolicyPeer
ioK8sApiNetworkingV1NetworkPolicyPeerDecoder =
    decode IoK8sApiNetworkingV1NetworkPolicyPeer
        |> optional "ipBlock" (Decode.nullable ioK8sApiNetworkingV1IPBlockDecoder) Nothing
        |> optional "namespaceSelector" (Decode.nullable ioK8sApimachineryPkgApisMetaV1LabelSelectorDecoder) Nothing
        |> optional "podSelector" (Decode.nullable ioK8sApimachineryPkgApisMetaV1LabelSelectorDecoder) Nothing



ioK8sApiNetworkingV1NetworkPolicyPeerEncoder : IoK8sApiNetworkingV1NetworkPolicyPeer -> Encode.Value
ioK8sApiNetworkingV1NetworkPolicyPeerEncoder model =
    Encode.object
        [ ( "ipBlock", withDefault Encode.null (map ioK8sApiNetworkingV1IPBlockEncoder model.ipBlock) )
        , ( "namespaceSelector", withDefault Encode.null (map ioK8sApimachineryPkgApisMetaV1LabelSelectorEncoder model.namespaceSelector) )
        , ( "podSelector", withDefault Encode.null (map ioK8sApimachineryPkgApisMetaV1LabelSelectorEncoder model.podSelector) )
        ]


