{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApimachineryPkgRuntimeRawExtension exposing (IoK8sApimachineryPkgRuntimeRawExtension, ioK8sApimachineryPkgRuntimeRawExtensionDecoder, ioK8sApimachineryPkgRuntimeRawExtensionEncoder)

import Byte exposing (Byte, byteDecoder, byteEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   RawExtension is used to hold extensions in external versions.  To use this, make a field which has RawExtension as its type in your external, versioned struct, and Object in your internal struct. You also need to register your various plugin types.  // Internal package: type MyAPIObject struct {  runtime.TypeMeta `json:\",inline\"`  MyPlugin runtime.Object `json:\"myPlugin\"` } type PluginA struct {  AOption string `json:\"aOption\"` }  // External package: type MyAPIObject struct {  runtime.TypeMeta `json:\",inline\"`  MyPlugin runtime.RawExtension `json:\"myPlugin\"` } type PluginA struct {  AOption string `json:\"aOption\"` }  // On the wire, the JSON will look something like this: {  \"kind\":\"MyAPIObject\",  \"apiVersion\":\"v1\",  \"myPlugin\": {   \"kind\":\"PluginA\",   \"aOption\":\"foo\",  }, }  So what happens? Decode first uses json or yaml to unmarshal the serialized data into your external MyAPIObject. That causes the raw JSON to be stored, but not unpacked. The next step is to copy (using pkg/conversion) into the internal struct. The runtime package's DefaultScheme has conversion functions installed which will unpack the JSON stored in RawExtension, turning it into the correct object type, and storing it in the Object. (TODO: In the case where the object is of an unknown type, a runtime.Unknown object will be created and stored.)
-}


type alias IoK8sApimachineryPkgRuntimeRawExtension =
    { raw : Byte
    }


ioK8sApimachineryPkgRuntimeRawExtensionDecoder : Decoder IoK8sApimachineryPkgRuntimeRawExtension
ioK8sApimachineryPkgRuntimeRawExtensionDecoder =
    decode IoK8sApimachineryPkgRuntimeRawExtension
        |> required "Raw" byteDecoder



ioK8sApimachineryPkgRuntimeRawExtensionEncoder : IoK8sApimachineryPkgRuntimeRawExtension -> Encode.Value
ioK8sApimachineryPkgRuntimeRawExtensionEncoder model =
    Encode.object
        [ ( "Raw", byteEncoder model.raw )
        ]


