{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiAutoscalingV2beta2MetricSpec exposing (IoK8sApiAutoscalingV2beta2MetricSpec, ioK8sApiAutoscalingV2beta2MetricSpecDecoder, ioK8sApiAutoscalingV2beta2MetricSpecEncoder)

import Data.IoK8sApiAutoscalingV2beta2ExternalMetricSource exposing (IoK8sApiAutoscalingV2beta2ExternalMetricSource, ioK8sApiAutoscalingV2beta2ExternalMetricSourceDecoder, ioK8sApiAutoscalingV2beta2ExternalMetricSourceEncoder)
import Data.IoK8sApiAutoscalingV2beta2ObjectMetricSource exposing (IoK8sApiAutoscalingV2beta2ObjectMetricSource, ioK8sApiAutoscalingV2beta2ObjectMetricSourceDecoder, ioK8sApiAutoscalingV2beta2ObjectMetricSourceEncoder)
import Data.IoK8sApiAutoscalingV2beta2PodsMetricSource exposing (IoK8sApiAutoscalingV2beta2PodsMetricSource, ioK8sApiAutoscalingV2beta2PodsMetricSourceDecoder, ioK8sApiAutoscalingV2beta2PodsMetricSourceEncoder)
import Data.IoK8sApiAutoscalingV2beta2ResourceMetricSource exposing (IoK8sApiAutoscalingV2beta2ResourceMetricSource, ioK8sApiAutoscalingV2beta2ResourceMetricSourceDecoder, ioK8sApiAutoscalingV2beta2ResourceMetricSourceEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   MetricSpec specifies how to scale based on a single metric (only `type` and one other matching field should be set at once).
-}


type alias IoK8sApiAutoscalingV2beta2MetricSpec =
    { external : Maybe IoK8sApiAutoscalingV2beta2ExternalMetricSource
    , object : Maybe IoK8sApiAutoscalingV2beta2ObjectMetricSource
    , pods : Maybe IoK8sApiAutoscalingV2beta2PodsMetricSource
    , resource : Maybe IoK8sApiAutoscalingV2beta2ResourceMetricSource
    , type_ : String
    }


ioK8sApiAutoscalingV2beta2MetricSpecDecoder : Decoder IoK8sApiAutoscalingV2beta2MetricSpec
ioK8sApiAutoscalingV2beta2MetricSpecDecoder =
    decode IoK8sApiAutoscalingV2beta2MetricSpec
        |> optional "external" (Decode.nullable ioK8sApiAutoscalingV2beta2ExternalMetricSourceDecoder) Nothing
        |> optional "object" (Decode.nullable ioK8sApiAutoscalingV2beta2ObjectMetricSourceDecoder) Nothing
        |> optional "pods" (Decode.nullable ioK8sApiAutoscalingV2beta2PodsMetricSourceDecoder) Nothing
        |> optional "resource" (Decode.nullable ioK8sApiAutoscalingV2beta2ResourceMetricSourceDecoder) Nothing
        |> required "type" Decode.string



ioK8sApiAutoscalingV2beta2MetricSpecEncoder : IoK8sApiAutoscalingV2beta2MetricSpec -> Encode.Value
ioK8sApiAutoscalingV2beta2MetricSpecEncoder model =
    Encode.object
        [ ( "external", withDefault Encode.null (map ioK8sApiAutoscalingV2beta2ExternalMetricSourceEncoder model.external) )
        , ( "object", withDefault Encode.null (map ioK8sApiAutoscalingV2beta2ObjectMetricSourceEncoder model.object) )
        , ( "pods", withDefault Encode.null (map ioK8sApiAutoscalingV2beta2PodsMetricSourceEncoder model.pods) )
        , ( "resource", withDefault Encode.null (map ioK8sApiAutoscalingV2beta2ResourceMetricSourceEncoder model.resource) )
        , ( "type", Encode.string model.type_ )
        ]


