{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiCoreV1ContainerStateRunning exposing (IoK8sApiCoreV1ContainerStateRunning, ioK8sApiCoreV1ContainerStateRunningDecoder, ioK8sApiCoreV1ContainerStateRunningEncoder)

import Data.IoK8sApimachineryPkgApisMetaV1Time exposing (IoK8sApimachineryPkgApisMetaV1Time, ioK8sApimachineryPkgApisMetaV1TimeDecoder, ioK8sApimachineryPkgApisMetaV1TimeEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   ContainerStateRunning is a running state of a container.
-}


type alias IoK8sApiCoreV1ContainerStateRunning =
    { startedAt : Maybe IoK8sApimachineryPkgApisMetaV1Time
    }


ioK8sApiCoreV1ContainerStateRunningDecoder : Decoder IoK8sApiCoreV1ContainerStateRunning
ioK8sApiCoreV1ContainerStateRunningDecoder =
    decode IoK8sApiCoreV1ContainerStateRunning
        |> optional "startedAt" (Decode.nullable ioK8sApimachineryPkgApisMetaV1TimeDecoder) Nothing



ioK8sApiCoreV1ContainerStateRunningEncoder : IoK8sApiCoreV1ContainerStateRunning -> Encode.Value
ioK8sApiCoreV1ContainerStateRunningEncoder model =
    Encode.object
        [ ( "startedAt", withDefault Encode.null (map ioK8sApimachineryPkgApisMetaV1TimeEncoder model.startedAt) )
        ]


