{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps exposing (IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsDecoder, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsEncoder)

import Data.IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsOrBool exposing (IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsOrBool, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsOrBoolDecoder, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsOrBoolEncoder)
import Data.IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsOrBool exposing (IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsOrBool, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsOrBoolDecoder, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsOrBoolEncoder)
import Data.IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps exposing (IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsDecoder, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsEncoder)
import Data.IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps exposing (IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsDecoder, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsEncoder)
import Data.IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSON exposing (IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSON, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONDecoder, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONEncoder)
import Data.IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps exposing (IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsDecoder, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsEncoder)
import Data.IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsOrStringArray exposing (IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsOrStringArray, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsOrStringArrayDecoder, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsOrStringArrayEncoder)
import Data.IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSON exposing (IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSON, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONDecoder, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONEncoder)
import Data.IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSON exposing (IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSON, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONDecoder, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONEncoder)
import Data.IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1ExternalDocumentation exposing (IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1ExternalDocumentation, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1ExternalDocumentationDecoder, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1ExternalDocumentationEncoder)
import Data.IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsOrArray exposing (IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsOrArray, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsOrArrayDecoder, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsOrArrayEncoder)
import Data.IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps exposing (IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsDecoder, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsEncoder)
import Data.IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps exposing (IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsDecoder, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsEncoder)
import Data.IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps exposing (IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsDecoder, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsEncoder)
import Data.IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps exposing (IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsDecoder, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   JSONSchemaProps is a JSON-Schema following Specification Draft 4 (http://json-schema.org/).
-}


type alias IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps =
    { $Ref : Maybe String
    , $Schema : Maybe String
    , additionalItems : Maybe IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsOrBool
    , additionalProperties : Maybe IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsOrBool
    , allOf : Maybe (List IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps)
    , anyOf : Maybe (List IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps)
    , default : Maybe IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSON
    , definitions : Maybe (List IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps)
    , dependencies : Maybe (List IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsOrStringArray)
    , description : Maybe String
    , enum : Maybe (List IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSON)
    , example : Maybe IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSON
    , exclusiveMaximum : Maybe Bool
    , exclusiveMinimum : Maybe Bool
    , externalDocs : Maybe IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1ExternalDocumentation
    , format : Maybe String
    , id : Maybe String
    , items : Maybe IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsOrArray
    , maxItems : Maybe Int
    , maxLength : Maybe Int
    , maxProperties : Maybe Int
    , maximum : Maybe Float
    , minItems : Maybe Int
    , minLength : Maybe Int
    , minProperties : Maybe Int
    , minimum : Maybe Float
    , multipleOf : Maybe Float
    , not : Maybe IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
    , oneOf : Maybe (List IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps)
    , pattern : Maybe String
    , patternProperties : Maybe (List IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps)
    , properties : Maybe (List IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps)
    , required : Maybe (List String)
    , title : Maybe String
    , type_ : Maybe String
    , uniqueItems : Maybe Bool
    }


ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsDecoder : Decoder IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsDecoder =
    decode IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
        |> optional "$ref" (Decode.nullable Decode.string) Nothing
        |> optional "$schema" (Decode.nullable Decode.string) Nothing
        |> optional "additionalItems" (Decode.nullable ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsOrBoolDecoder) Nothing
        |> optional "additionalProperties" (Decode.nullable ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsOrBoolDecoder) Nothing
        |> optional "allOf" (Decode.nullable (Decode.list ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsDecoder)) Nothing
        |> optional "anyOf" (Decode.nullable (Decode.list ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsDecoder)) Nothing
        |> optional "default" (Decode.nullable ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONDecoder) Nothing
        |> optional "definitions" (Decode.nullable (Decode.list ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsDecoder)) Nothing
        |> optional "dependencies" (Decode.nullable (Decode.list ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsOrStringArrayDecoder)) Nothing
        |> optional "description" (Decode.nullable Decode.string) Nothing
        |> optional "enum" (Decode.nullable (Decode.list ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONDecoder)) Nothing
        |> optional "example" (Decode.nullable ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONDecoder) Nothing
        |> optional "exclusiveMaximum" (Decode.nullable Decode.bool) Nothing
        |> optional "exclusiveMinimum" (Decode.nullable Decode.bool) Nothing
        |> optional "externalDocs" (Decode.nullable ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1ExternalDocumentationDecoder) Nothing
        |> optional "format" (Decode.nullable Decode.string) Nothing
        |> optional "id" (Decode.nullable Decode.string) Nothing
        |> optional "items" (Decode.nullable ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsOrArrayDecoder) Nothing
        |> optional "maxItems" (Decode.nullable Decode.int) Nothing
        |> optional "maxLength" (Decode.nullable Decode.int) Nothing
        |> optional "maxProperties" (Decode.nullable Decode.int) Nothing
        |> optional "maximum" (Decode.nullable Decode.float) Nothing
        |> optional "minItems" (Decode.nullable Decode.int) Nothing
        |> optional "minLength" (Decode.nullable Decode.int) Nothing
        |> optional "minProperties" (Decode.nullable Decode.int) Nothing
        |> optional "minimum" (Decode.nullable Decode.float) Nothing
        |> optional "multipleOf" (Decode.nullable Decode.float) Nothing
        |> optional "not" (Decode.nullable ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsDecoder) Nothing
        |> optional "oneOf" (Decode.nullable (Decode.list ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsDecoder)) Nothing
        |> optional "pattern" (Decode.nullable Decode.string) Nothing
        |> optional "patternProperties" (Decode.nullable (Decode.list ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsDecoder)) Nothing
        |> optional "properties" (Decode.nullable (Decode.list ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsDecoder)) Nothing
        |> optional "required" (Decode.nullable (Decode.list Decode.string)) Nothing
        |> optional "title" (Decode.nullable Decode.string) Nothing
        |> optional "type" (Decode.nullable Decode.string) Nothing
        |> optional "uniqueItems" (Decode.nullable Decode.bool) Nothing



ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsEncoder : IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps -> Encode.Value
ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsEncoder model =
    Encode.object
        [ ( "$ref", withDefault Encode.null (map Encode.string model.$Ref) )
        , ( "$schema", withDefault Encode.null (map Encode.string model.$Schema) )
        , ( "additionalItems", withDefault Encode.null (map ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsOrBoolEncoder model.additionalItems) )
        , ( "additionalProperties", withDefault Encode.null (map ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsOrBoolEncoder model.additionalProperties) )
        , ( "allOf", withDefault Encode.null (map (Encode.list << List.map ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsEncoder) model.allOf) )
        , ( "anyOf", withDefault Encode.null (map (Encode.list << List.map ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsEncoder) model.anyOf) )
        , ( "default", withDefault Encode.null (map ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONEncoder model.default) )
        , ( "definitions", withDefault Encode.null (map (Encode.list << List.map ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsEncoder) model.definitions) )
        , ( "dependencies", withDefault Encode.null (map (Encode.list << List.map ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsOrStringArrayEncoder) model.dependencies) )
        , ( "description", withDefault Encode.null (map Encode.string model.description) )
        , ( "enum", withDefault Encode.null (map (Encode.list << List.map ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONEncoder) model.enum) )
        , ( "example", withDefault Encode.null (map ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONEncoder model.example) )
        , ( "exclusiveMaximum", withDefault Encode.null (map Encode.bool model.exclusiveMaximum) )
        , ( "exclusiveMinimum", withDefault Encode.null (map Encode.bool model.exclusiveMinimum) )
        , ( "externalDocs", withDefault Encode.null (map ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1ExternalDocumentationEncoder model.externalDocs) )
        , ( "format", withDefault Encode.null (map Encode.string model.format) )
        , ( "id", withDefault Encode.null (map Encode.string model.id) )
        , ( "items", withDefault Encode.null (map ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsOrArrayEncoder model.items) )
        , ( "maxItems", withDefault Encode.null (map Encode.int model.maxItems) )
        , ( "maxLength", withDefault Encode.null (map Encode.int model.maxLength) )
        , ( "maxProperties", withDefault Encode.null (map Encode.int model.maxProperties) )
        , ( "maximum", withDefault Encode.null (map Encode.float model.maximum) )
        , ( "minItems", withDefault Encode.null (map Encode.int model.minItems) )
        , ( "minLength", withDefault Encode.null (map Encode.int model.minLength) )
        , ( "minProperties", withDefault Encode.null (map Encode.int model.minProperties) )
        , ( "minimum", withDefault Encode.null (map Encode.float model.minimum) )
        , ( "multipleOf", withDefault Encode.null (map Encode.float model.multipleOf) )
        , ( "not", withDefault Encode.null (map ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsEncoder model.not) )
        , ( "oneOf", withDefault Encode.null (map (Encode.list << List.map ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsEncoder) model.oneOf) )
        , ( "pattern", withDefault Encode.null (map Encode.string model.pattern) )
        , ( "patternProperties", withDefault Encode.null (map (Encode.list << List.map ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsEncoder) model.patternProperties) )
        , ( "properties", withDefault Encode.null (map (Encode.list << List.map ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsEncoder) model.properties) )
        , ( "required", withDefault Encode.null (map (Encode.list << List.map Encode.string) model.required) )
        , ( "title", withDefault Encode.null (map Encode.string model.title) )
        , ( "type", withDefault Encode.null (map Encode.string model.type_) )
        , ( "uniqueItems", withDefault Encode.null (map Encode.bool model.uniqueItems) )
        ]


