{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiCoreV1PodTemplate exposing (IoK8sApiCoreV1PodTemplate, ioK8sApiCoreV1PodTemplateDecoder, ioK8sApiCoreV1PodTemplateEncoder)

import Data.IoK8sApimachineryPkgApisMetaV1ObjectMeta exposing (IoK8sApimachineryPkgApisMetaV1ObjectMeta, ioK8sApimachineryPkgApisMetaV1ObjectMetaDecoder, ioK8sApimachineryPkgApisMetaV1ObjectMetaEncoder)
import Data.IoK8sApiCoreV1PodTemplateSpec exposing (IoK8sApiCoreV1PodTemplateSpec, ioK8sApiCoreV1PodTemplateSpecDecoder, ioK8sApiCoreV1PodTemplateSpecEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   PodTemplate describes a template for creating copies of a predefined pod.
-}


type alias IoK8sApiCoreV1PodTemplate =
    { apiVersion : Maybe String
    , kind : Maybe String
    , metadata : Maybe IoK8sApimachineryPkgApisMetaV1ObjectMeta
    , template : Maybe IoK8sApiCoreV1PodTemplateSpec
    }


ioK8sApiCoreV1PodTemplateDecoder : Decoder IoK8sApiCoreV1PodTemplate
ioK8sApiCoreV1PodTemplateDecoder =
    decode IoK8sApiCoreV1PodTemplate
        |> optional "apiVersion" (Decode.nullable Decode.string) Nothing
        |> optional "kind" (Decode.nullable Decode.string) Nothing
        |> optional "metadata" (Decode.nullable ioK8sApimachineryPkgApisMetaV1ObjectMetaDecoder) Nothing
        |> optional "template" (Decode.nullable ioK8sApiCoreV1PodTemplateSpecDecoder) Nothing



ioK8sApiCoreV1PodTemplateEncoder : IoK8sApiCoreV1PodTemplate -> Encode.Value
ioK8sApiCoreV1PodTemplateEncoder model =
    Encode.object
        [ ( "apiVersion", withDefault Encode.null (map Encode.string model.apiVersion) )
        , ( "kind", withDefault Encode.null (map Encode.string model.kind) )
        , ( "metadata", withDefault Encode.null (map ioK8sApimachineryPkgApisMetaV1ObjectMetaEncoder model.metadata) )
        , ( "template", withDefault Encode.null (map ioK8sApiCoreV1PodTemplateSpecEncoder model.template) )
        ]


