{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiAutoscalingV2beta2ExternalMetricStatus exposing (IoK8sApiAutoscalingV2beta2ExternalMetricStatus, ioK8sApiAutoscalingV2beta2ExternalMetricStatusDecoder, ioK8sApiAutoscalingV2beta2ExternalMetricStatusEncoder)

import Data.IoK8sApiAutoscalingV2beta2MetricValueStatus exposing (IoK8sApiAutoscalingV2beta2MetricValueStatus, ioK8sApiAutoscalingV2beta2MetricValueStatusDecoder, ioK8sApiAutoscalingV2beta2MetricValueStatusEncoder)
import Data.IoK8sApiAutoscalingV2beta2MetricIdentifier exposing (IoK8sApiAutoscalingV2beta2MetricIdentifier, ioK8sApiAutoscalingV2beta2MetricIdentifierDecoder, ioK8sApiAutoscalingV2beta2MetricIdentifierEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   ExternalMetricStatus indicates the current value of a global metric not associated with any Kubernetes object.
-}


type alias IoK8sApiAutoscalingV2beta2ExternalMetricStatus =
    { current : IoK8sApiAutoscalingV2beta2MetricValueStatus
    , metric : IoK8sApiAutoscalingV2beta2MetricIdentifier
    }


ioK8sApiAutoscalingV2beta2ExternalMetricStatusDecoder : Decoder IoK8sApiAutoscalingV2beta2ExternalMetricStatus
ioK8sApiAutoscalingV2beta2ExternalMetricStatusDecoder =
    decode IoK8sApiAutoscalingV2beta2ExternalMetricStatus
        |> required "current" ioK8sApiAutoscalingV2beta2MetricValueStatusDecoder
        |> required "metric" ioK8sApiAutoscalingV2beta2MetricIdentifierDecoder



ioK8sApiAutoscalingV2beta2ExternalMetricStatusEncoder : IoK8sApiAutoscalingV2beta2ExternalMetricStatus -> Encode.Value
ioK8sApiAutoscalingV2beta2ExternalMetricStatusEncoder model =
    Encode.object
        [ ( "current", ioK8sApiAutoscalingV2beta2MetricValueStatusEncoder model.current )
        , ( "metric", ioK8sApiAutoscalingV2beta2MetricIdentifierEncoder model.metric )
        ]


