{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiBatchV1JobStatus exposing (IoK8sApiBatchV1JobStatus, ioK8sApiBatchV1JobStatusDecoder, ioK8sApiBatchV1JobStatusEncoder)

import Data.IoK8sApimachineryPkgApisMetaV1Time exposing (IoK8sApimachineryPkgApisMetaV1Time, ioK8sApimachineryPkgApisMetaV1TimeDecoder, ioK8sApimachineryPkgApisMetaV1TimeEncoder)
import Data.IoK8sApiBatchV1JobCondition exposing (IoK8sApiBatchV1JobCondition, ioK8sApiBatchV1JobConditionDecoder, ioK8sApiBatchV1JobConditionEncoder)
import Data.IoK8sApimachineryPkgApisMetaV1Time exposing (IoK8sApimachineryPkgApisMetaV1Time, ioK8sApimachineryPkgApisMetaV1TimeDecoder, ioK8sApimachineryPkgApisMetaV1TimeEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   JobStatus represents the current state of a Job.
-}


type alias IoK8sApiBatchV1JobStatus =
    { active : Maybe Int
    , completionTime : Maybe IoK8sApimachineryPkgApisMetaV1Time
    , conditions : Maybe (List IoK8sApiBatchV1JobCondition)
    , failed : Maybe Int
    , startTime : Maybe IoK8sApimachineryPkgApisMetaV1Time
    , succeeded : Maybe Int
    }


ioK8sApiBatchV1JobStatusDecoder : Decoder IoK8sApiBatchV1JobStatus
ioK8sApiBatchV1JobStatusDecoder =
    decode IoK8sApiBatchV1JobStatus
        |> optional "active" (Decode.nullable Decode.int) Nothing
        |> optional "completionTime" (Decode.nullable ioK8sApimachineryPkgApisMetaV1TimeDecoder) Nothing
        |> optional "conditions" (Decode.nullable (Decode.list ioK8sApiBatchV1JobConditionDecoder)) Nothing
        |> optional "failed" (Decode.nullable Decode.int) Nothing
        |> optional "startTime" (Decode.nullable ioK8sApimachineryPkgApisMetaV1TimeDecoder) Nothing
        |> optional "succeeded" (Decode.nullable Decode.int) Nothing



ioK8sApiBatchV1JobStatusEncoder : IoK8sApiBatchV1JobStatus -> Encode.Value
ioK8sApiBatchV1JobStatusEncoder model =
    Encode.object
        [ ( "active", withDefault Encode.null (map Encode.int model.active) )
        , ( "completionTime", withDefault Encode.null (map ioK8sApimachineryPkgApisMetaV1TimeEncoder model.completionTime) )
        , ( "conditions", withDefault Encode.null (map (Encode.list << List.map ioK8sApiBatchV1JobConditionEncoder) model.conditions) )
        , ( "failed", withDefault Encode.null (map Encode.int model.failed) )
        , ( "startTime", withDefault Encode.null (map ioK8sApimachineryPkgApisMetaV1TimeEncoder model.startTime) )
        , ( "succeeded", withDefault Encode.null (map Encode.int model.succeeded) )
        ]


