{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiRbacV1beta1PolicyRule exposing (IoK8sApiRbacV1beta1PolicyRule, ioK8sApiRbacV1beta1PolicyRuleDecoder, ioK8sApiRbacV1beta1PolicyRuleEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   PolicyRule holds information that describes a policy rule, but does not contain information about who the rule applies to or which namespace the rule applies to.
-}


type alias IoK8sApiRbacV1beta1PolicyRule =
    { apiGroups : Maybe (List String)
    , nonResourceURLs : Maybe (List String)
    , resourceNames : Maybe (List String)
    , resources : Maybe (List String)
    , verbs : (List String)
    }


ioK8sApiRbacV1beta1PolicyRuleDecoder : Decoder IoK8sApiRbacV1beta1PolicyRule
ioK8sApiRbacV1beta1PolicyRuleDecoder =
    decode IoK8sApiRbacV1beta1PolicyRule
        |> optional "apiGroups" (Decode.nullable (Decode.list Decode.string)) Nothing
        |> optional "nonResourceURLs" (Decode.nullable (Decode.list Decode.string)) Nothing
        |> optional "resourceNames" (Decode.nullable (Decode.list Decode.string)) Nothing
        |> optional "resources" (Decode.nullable (Decode.list Decode.string)) Nothing
        |> required "verbs" (Decode.list Decode.string)



ioK8sApiRbacV1beta1PolicyRuleEncoder : IoK8sApiRbacV1beta1PolicyRule -> Encode.Value
ioK8sApiRbacV1beta1PolicyRuleEncoder model =
    Encode.object
        [ ( "apiGroups", withDefault Encode.null (map (Encode.list << List.map Encode.string) model.apiGroups) )
        , ( "nonResourceURLs", withDefault Encode.null (map (Encode.list << List.map Encode.string) model.nonResourceURLs) )
        , ( "resourceNames", withDefault Encode.null (map (Encode.list << List.map Encode.string) model.resourceNames) )
        , ( "resources", withDefault Encode.null (map (Encode.list << List.map Encode.string) model.resources) )
        , ( "verbs", (Encode.list << List.map Encode.string) model.verbs )
        ]


