{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiCoreV1ServiceAccount exposing (IoK8sApiCoreV1ServiceAccount, ioK8sApiCoreV1ServiceAccountDecoder, ioK8sApiCoreV1ServiceAccountEncoder)

import Data.IoK8sApiCoreV1LocalObjectReference exposing (IoK8sApiCoreV1LocalObjectReference, ioK8sApiCoreV1LocalObjectReferenceDecoder, ioK8sApiCoreV1LocalObjectReferenceEncoder)
import Data.IoK8sApimachineryPkgApisMetaV1ObjectMeta exposing (IoK8sApimachineryPkgApisMetaV1ObjectMeta, ioK8sApimachineryPkgApisMetaV1ObjectMetaDecoder, ioK8sApimachineryPkgApisMetaV1ObjectMetaEncoder)
import Data.IoK8sApiCoreV1ObjectReference exposing (IoK8sApiCoreV1ObjectReference, ioK8sApiCoreV1ObjectReferenceDecoder, ioK8sApiCoreV1ObjectReferenceEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   ServiceAccount binds together: * a name, understood by users, and perhaps by peripheral systems, for an identity * a principal that can be authenticated and authorized * a set of secrets
-}


type alias IoK8sApiCoreV1ServiceAccount =
    { apiVersion : Maybe String
    , automountServiceAccountToken : Maybe Bool
    , imagePullSecrets : Maybe (List IoK8sApiCoreV1LocalObjectReference)
    , kind : Maybe String
    , metadata : Maybe IoK8sApimachineryPkgApisMetaV1ObjectMeta
    , secrets : Maybe (List IoK8sApiCoreV1ObjectReference)
    }


ioK8sApiCoreV1ServiceAccountDecoder : Decoder IoK8sApiCoreV1ServiceAccount
ioK8sApiCoreV1ServiceAccountDecoder =
    decode IoK8sApiCoreV1ServiceAccount
        |> optional "apiVersion" (Decode.nullable Decode.string) Nothing
        |> optional "automountServiceAccountToken" (Decode.nullable Decode.bool) Nothing
        |> optional "imagePullSecrets" (Decode.nullable (Decode.list ioK8sApiCoreV1LocalObjectReferenceDecoder)) Nothing
        |> optional "kind" (Decode.nullable Decode.string) Nothing
        |> optional "metadata" (Decode.nullable ioK8sApimachineryPkgApisMetaV1ObjectMetaDecoder) Nothing
        |> optional "secrets" (Decode.nullable (Decode.list ioK8sApiCoreV1ObjectReferenceDecoder)) Nothing



ioK8sApiCoreV1ServiceAccountEncoder : IoK8sApiCoreV1ServiceAccount -> Encode.Value
ioK8sApiCoreV1ServiceAccountEncoder model =
    Encode.object
        [ ( "apiVersion", withDefault Encode.null (map Encode.string model.apiVersion) )
        , ( "automountServiceAccountToken", withDefault Encode.null (map Encode.bool model.automountServiceAccountToken) )
        , ( "imagePullSecrets", withDefault Encode.null (map (Encode.list << List.map ioK8sApiCoreV1LocalObjectReferenceEncoder) model.imagePullSecrets) )
        , ( "kind", withDefault Encode.null (map Encode.string model.kind) )
        , ( "metadata", withDefault Encode.null (map ioK8sApimachineryPkgApisMetaV1ObjectMetaEncoder model.metadata) )
        , ( "secrets", withDefault Encode.null (map (Encode.list << List.map ioK8sApiCoreV1ObjectReferenceEncoder) model.secrets) )
        ]


