{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiAppsV1Deployment exposing (IoK8sApiAppsV1Deployment, ioK8sApiAppsV1DeploymentDecoder, ioK8sApiAppsV1DeploymentEncoder)

import Data.IoK8sApimachineryPkgApisMetaV1ObjectMeta exposing (IoK8sApimachineryPkgApisMetaV1ObjectMeta, ioK8sApimachineryPkgApisMetaV1ObjectMetaDecoder, ioK8sApimachineryPkgApisMetaV1ObjectMetaEncoder)
import Data.IoK8sApiAppsV1DeploymentSpec exposing (IoK8sApiAppsV1DeploymentSpec, ioK8sApiAppsV1DeploymentSpecDecoder, ioK8sApiAppsV1DeploymentSpecEncoder)
import Data.IoK8sApiAppsV1DeploymentStatus exposing (IoK8sApiAppsV1DeploymentStatus, ioK8sApiAppsV1DeploymentStatusDecoder, ioK8sApiAppsV1DeploymentStatusEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   Deployment enables declarative updates for Pods and ReplicaSets.
-}


type alias IoK8sApiAppsV1Deployment =
    { apiVersion : Maybe String
    , kind : Maybe String
    , metadata : Maybe IoK8sApimachineryPkgApisMetaV1ObjectMeta
    , spec : Maybe IoK8sApiAppsV1DeploymentSpec
    , status : Maybe IoK8sApiAppsV1DeploymentStatus
    }


ioK8sApiAppsV1DeploymentDecoder : Decoder IoK8sApiAppsV1Deployment
ioK8sApiAppsV1DeploymentDecoder =
    decode IoK8sApiAppsV1Deployment
        |> optional "apiVersion" (Decode.nullable Decode.string) Nothing
        |> optional "kind" (Decode.nullable Decode.string) Nothing
        |> optional "metadata" (Decode.nullable ioK8sApimachineryPkgApisMetaV1ObjectMetaDecoder) Nothing
        |> optional "spec" (Decode.nullable ioK8sApiAppsV1DeploymentSpecDecoder) Nothing
        |> optional "status" (Decode.nullable ioK8sApiAppsV1DeploymentStatusDecoder) Nothing



ioK8sApiAppsV1DeploymentEncoder : IoK8sApiAppsV1Deployment -> Encode.Value
ioK8sApiAppsV1DeploymentEncoder model =
    Encode.object
        [ ( "apiVersion", withDefault Encode.null (map Encode.string model.apiVersion) )
        , ( "kind", withDefault Encode.null (map Encode.string model.kind) )
        , ( "metadata", withDefault Encode.null (map ioK8sApimachineryPkgApisMetaV1ObjectMetaEncoder model.metadata) )
        , ( "spec", withDefault Encode.null (map ioK8sApiAppsV1DeploymentSpecEncoder model.spec) )
        , ( "status", withDefault Encode.null (map ioK8sApiAppsV1DeploymentStatusEncoder model.status) )
        ]


