{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiCoreV1Secret exposing (IoK8sApiCoreV1Secret, ioK8sApiCoreV1SecretDecoder, ioK8sApiCoreV1SecretEncoder)

import Byte exposing (Byte, byteDecoder, byteEncoder)
import Data.IoK8sApimachineryPkgApisMetaV1ObjectMeta exposing (IoK8sApimachineryPkgApisMetaV1ObjectMeta, ioK8sApimachineryPkgApisMetaV1ObjectMetaDecoder, ioK8sApimachineryPkgApisMetaV1ObjectMetaEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   Secret holds secret data of a certain type. The total bytes of the values in the Data field must be less than MaxSecretSize bytes.
-}


type alias IoK8sApiCoreV1Secret =
    { apiVersion : Maybe String
    , data : Maybe (List Byte)
    , kind : Maybe String
    , metadata : Maybe IoK8sApimachineryPkgApisMetaV1ObjectMeta
    , stringData : Maybe (List String)
    , type_ : Maybe String
    }


ioK8sApiCoreV1SecretDecoder : Decoder IoK8sApiCoreV1Secret
ioK8sApiCoreV1SecretDecoder =
    decode IoK8sApiCoreV1Secret
        |> optional "apiVersion" (Decode.nullable Decode.string) Nothing
        |> optional "data" (Decode.nullable (Decode.list byteDecoder)) Nothing
        |> optional "kind" (Decode.nullable Decode.string) Nothing
        |> optional "metadata" (Decode.nullable ioK8sApimachineryPkgApisMetaV1ObjectMetaDecoder) Nothing
        |> optional "stringData" (Decode.nullable (Decode.list Decode.string)) Nothing
        |> optional "type" (Decode.nullable Decode.string) Nothing



ioK8sApiCoreV1SecretEncoder : IoK8sApiCoreV1Secret -> Encode.Value
ioK8sApiCoreV1SecretEncoder model =
    Encode.object
        [ ( "apiVersion", withDefault Encode.null (map Encode.string model.apiVersion) )
        , ( "data", withDefault Encode.null (map (Encode.list << List.map byteEncoder) model.data) )
        , ( "kind", withDefault Encode.null (map Encode.string model.kind) )
        , ( "metadata", withDefault Encode.null (map ioK8sApimachineryPkgApisMetaV1ObjectMetaEncoder model.metadata) )
        , ( "stringData", withDefault Encode.null (map (Encode.list << List.map Encode.string) model.stringData) )
        , ( "type", withDefault Encode.null (map Encode.string model.type_) )
        ]


