{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiCoreV1LoadBalancerStatus exposing (IoK8sApiCoreV1LoadBalancerStatus, ioK8sApiCoreV1LoadBalancerStatusDecoder, ioK8sApiCoreV1LoadBalancerStatusEncoder)

import Data.IoK8sApiCoreV1LoadBalancerIngress exposing (IoK8sApiCoreV1LoadBalancerIngress, ioK8sApiCoreV1LoadBalancerIngressDecoder, ioK8sApiCoreV1LoadBalancerIngressEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   LoadBalancerStatus represents the status of a load-balancer.
-}


type alias IoK8sApiCoreV1LoadBalancerStatus =
    { ingress : Maybe (List IoK8sApiCoreV1LoadBalancerIngress)
    }


ioK8sApiCoreV1LoadBalancerStatusDecoder : Decoder IoK8sApiCoreV1LoadBalancerStatus
ioK8sApiCoreV1LoadBalancerStatusDecoder =
    decode IoK8sApiCoreV1LoadBalancerStatus
        |> optional "ingress" (Decode.nullable (Decode.list ioK8sApiCoreV1LoadBalancerIngressDecoder)) Nothing



ioK8sApiCoreV1LoadBalancerStatusEncoder : IoK8sApiCoreV1LoadBalancerStatus -> Encode.Value
ioK8sApiCoreV1LoadBalancerStatusEncoder model =
    Encode.object
        [ ( "ingress", withDefault Encode.null (map (Encode.list << List.map ioK8sApiCoreV1LoadBalancerIngressEncoder) model.ingress) )
        ]


