{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiAdmissionregistrationV1beta1RuleWithOperations exposing (IoK8sApiAdmissionregistrationV1beta1RuleWithOperations, ioK8sApiAdmissionregistrationV1beta1RuleWithOperationsDecoder, ioK8sApiAdmissionregistrationV1beta1RuleWithOperationsEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   RuleWithOperations is a tuple of Operations and Resources. It is recommended to make sure that all the tuple expansions are valid.
-}


type alias IoK8sApiAdmissionregistrationV1beta1RuleWithOperations =
    { apiGroups : Maybe (List String)
    , apiVersions : Maybe (List String)
    , operations : Maybe (List String)
    , resources : Maybe (List String)
    }


ioK8sApiAdmissionregistrationV1beta1RuleWithOperationsDecoder : Decoder IoK8sApiAdmissionregistrationV1beta1RuleWithOperations
ioK8sApiAdmissionregistrationV1beta1RuleWithOperationsDecoder =
    decode IoK8sApiAdmissionregistrationV1beta1RuleWithOperations
        |> optional "apiGroups" (Decode.nullable (Decode.list Decode.string)) Nothing
        |> optional "apiVersions" (Decode.nullable (Decode.list Decode.string)) Nothing
        |> optional "operations" (Decode.nullable (Decode.list Decode.string)) Nothing
        |> optional "resources" (Decode.nullable (Decode.list Decode.string)) Nothing



ioK8sApiAdmissionregistrationV1beta1RuleWithOperationsEncoder : IoK8sApiAdmissionregistrationV1beta1RuleWithOperations -> Encode.Value
ioK8sApiAdmissionregistrationV1beta1RuleWithOperationsEncoder model =
    Encode.object
        [ ( "apiGroups", withDefault Encode.null (map (Encode.list << List.map Encode.string) model.apiGroups) )
        , ( "apiVersions", withDefault Encode.null (map (Encode.list << List.map Encode.string) model.apiVersions) )
        , ( "operations", withDefault Encode.null (map (Encode.list << List.map Encode.string) model.operations) )
        , ( "resources", withDefault Encode.null (map (Encode.list << List.map Encode.string) model.resources) )
        ]


