{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiCoreV1PersistentVolumeList exposing (IoK8sApiCoreV1PersistentVolumeList, ioK8sApiCoreV1PersistentVolumeListDecoder, ioK8sApiCoreV1PersistentVolumeListEncoder)

import Data.IoK8sApiCoreV1PersistentVolume exposing (IoK8sApiCoreV1PersistentVolume, ioK8sApiCoreV1PersistentVolumeDecoder, ioK8sApiCoreV1PersistentVolumeEncoder)
import Data.IoK8sApimachineryPkgApisMetaV1ListMeta exposing (IoK8sApimachineryPkgApisMetaV1ListMeta, ioK8sApimachineryPkgApisMetaV1ListMetaDecoder, ioK8sApimachineryPkgApisMetaV1ListMetaEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   PersistentVolumeList is a list of PersistentVolume items.
-}


type alias IoK8sApiCoreV1PersistentVolumeList =
    { apiVersion : Maybe String
    , items : (List IoK8sApiCoreV1PersistentVolume)
    , kind : Maybe String
    , metadata : Maybe IoK8sApimachineryPkgApisMetaV1ListMeta
    }


ioK8sApiCoreV1PersistentVolumeListDecoder : Decoder IoK8sApiCoreV1PersistentVolumeList
ioK8sApiCoreV1PersistentVolumeListDecoder =
    decode IoK8sApiCoreV1PersistentVolumeList
        |> optional "apiVersion" (Decode.nullable Decode.string) Nothing
        |> required "items" (Decode.list ioK8sApiCoreV1PersistentVolumeDecoder)
        |> optional "kind" (Decode.nullable Decode.string) Nothing
        |> optional "metadata" (Decode.nullable ioK8sApimachineryPkgApisMetaV1ListMetaDecoder) Nothing



ioK8sApiCoreV1PersistentVolumeListEncoder : IoK8sApiCoreV1PersistentVolumeList -> Encode.Value
ioK8sApiCoreV1PersistentVolumeListEncoder model =
    Encode.object
        [ ( "apiVersion", withDefault Encode.null (map Encode.string model.apiVersion) )
        , ( "items", (Encode.list << List.map ioK8sApiCoreV1PersistentVolumeEncoder) model.items )
        , ( "kind", withDefault Encode.null (map Encode.string model.kind) )
        , ( "metadata", withDefault Encode.null (map ioK8sApimachineryPkgApisMetaV1ListMetaEncoder model.metadata) )
        ]


