{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceConversion exposing (IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceConversion, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceConversionDecoder, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceConversionEncoder)

import Data.IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1WebhookClientConfig exposing (IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1WebhookClientConfig, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1WebhookClientConfigDecoder, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1WebhookClientConfigEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   CustomResourceConversion describes how to convert different versions of a CR.
-}


type alias IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceConversion =
    { strategy : String
    , webhookClientConfig : Maybe IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1WebhookClientConfig
    }


ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceConversionDecoder : Decoder IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceConversion
ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceConversionDecoder =
    decode IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceConversion
        |> required "strategy" Decode.string
        |> optional "webhookClientConfig" (Decode.nullable ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1WebhookClientConfigDecoder) Nothing



ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceConversionEncoder : IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceConversion -> Encode.Value
ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceConversionEncoder model =
    Encode.object
        [ ( "strategy", Encode.string model.strategy )
        , ( "webhookClientConfig", withDefault Encode.null (map ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1WebhookClientConfigEncoder model.webhookClientConfig) )
        ]


