{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiCoreV1PodSpec exposing (IoK8sApiCoreV1PodSpec, ioK8sApiCoreV1PodSpecDecoder, ioK8sApiCoreV1PodSpecEncoder)

import Data.IoK8sApiCoreV1Affinity exposing (IoK8sApiCoreV1Affinity, ioK8sApiCoreV1AffinityDecoder, ioK8sApiCoreV1AffinityEncoder)
import Data.IoK8sApiCoreV1Container exposing (IoK8sApiCoreV1Container, ioK8sApiCoreV1ContainerDecoder, ioK8sApiCoreV1ContainerEncoder)
import Data.IoK8sApiCoreV1PodDNSConfig exposing (IoK8sApiCoreV1PodDNSConfig, ioK8sApiCoreV1PodDNSConfigDecoder, ioK8sApiCoreV1PodDNSConfigEncoder)
import Data.IoK8sApiCoreV1HostAlias exposing (IoK8sApiCoreV1HostAlias, ioK8sApiCoreV1HostAliasDecoder, ioK8sApiCoreV1HostAliasEncoder)
import Data.IoK8sApiCoreV1LocalObjectReference exposing (IoK8sApiCoreV1LocalObjectReference, ioK8sApiCoreV1LocalObjectReferenceDecoder, ioK8sApiCoreV1LocalObjectReferenceEncoder)
import Data.IoK8sApiCoreV1Container exposing (IoK8sApiCoreV1Container, ioK8sApiCoreV1ContainerDecoder, ioK8sApiCoreV1ContainerEncoder)
import Data.IoK8sApiCoreV1PodReadinessGate exposing (IoK8sApiCoreV1PodReadinessGate, ioK8sApiCoreV1PodReadinessGateDecoder, ioK8sApiCoreV1PodReadinessGateEncoder)
import Data.IoK8sApiCoreV1PodSecurityContext exposing (IoK8sApiCoreV1PodSecurityContext, ioK8sApiCoreV1PodSecurityContextDecoder, ioK8sApiCoreV1PodSecurityContextEncoder)
import Data.IoK8sApiCoreV1Toleration exposing (IoK8sApiCoreV1Toleration, ioK8sApiCoreV1TolerationDecoder, ioK8sApiCoreV1TolerationEncoder)
import Data.IoK8sApiCoreV1Volume exposing (IoK8sApiCoreV1Volume, ioK8sApiCoreV1VolumeDecoder, ioK8sApiCoreV1VolumeEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   PodSpec is a description of a pod.
-}


type alias IoK8sApiCoreV1PodSpec =
    { activeDeadlineSeconds : Maybe Int
    , affinity : Maybe IoK8sApiCoreV1Affinity
    , automountServiceAccountToken : Maybe Bool
    , containers : (List IoK8sApiCoreV1Container)
    , dnsConfig : Maybe IoK8sApiCoreV1PodDNSConfig
    , dnsPolicy : Maybe String
    , enableServiceLinks : Maybe Bool
    , hostAliases : Maybe (List IoK8sApiCoreV1HostAlias)
    , hostIPC : Maybe Bool
    , hostNetwork : Maybe Bool
    , hostPID : Maybe Bool
    , hostname : Maybe String
    , imagePullSecrets : Maybe (List IoK8sApiCoreV1LocalObjectReference)
    , initContainers : Maybe (List IoK8sApiCoreV1Container)
    , nodeName : Maybe String
    , nodeSelector : Maybe (List String)
    , priority : Maybe Int
    , priorityClassName : Maybe String
    , readinessGates : Maybe (List IoK8sApiCoreV1PodReadinessGate)
    , restartPolicy : Maybe String
    , runtimeClassName : Maybe String
    , schedulerName : Maybe String
    , securityContext : Maybe IoK8sApiCoreV1PodSecurityContext
    , serviceAccount : Maybe String
    , serviceAccountName : Maybe String
    , shareProcessNamespace : Maybe Bool
    , subdomain : Maybe String
    , terminationGracePeriodSeconds : Maybe Int
    , tolerations : Maybe (List IoK8sApiCoreV1Toleration)
    , volumes : Maybe (List IoK8sApiCoreV1Volume)
    }


ioK8sApiCoreV1PodSpecDecoder : Decoder IoK8sApiCoreV1PodSpec
ioK8sApiCoreV1PodSpecDecoder =
    decode IoK8sApiCoreV1PodSpec
        |> optional "activeDeadlineSeconds" (Decode.nullable Decode.int) Nothing
        |> optional "affinity" (Decode.nullable ioK8sApiCoreV1AffinityDecoder) Nothing
        |> optional "automountServiceAccountToken" (Decode.nullable Decode.bool) Nothing
        |> required "containers" (Decode.list ioK8sApiCoreV1ContainerDecoder)
        |> optional "dnsConfig" (Decode.nullable ioK8sApiCoreV1PodDNSConfigDecoder) Nothing
        |> optional "dnsPolicy" (Decode.nullable Decode.string) Nothing
        |> optional "enableServiceLinks" (Decode.nullable Decode.bool) Nothing
        |> optional "hostAliases" (Decode.nullable (Decode.list ioK8sApiCoreV1HostAliasDecoder)) Nothing
        |> optional "hostIPC" (Decode.nullable Decode.bool) Nothing
        |> optional "hostNetwork" (Decode.nullable Decode.bool) Nothing
        |> optional "hostPID" (Decode.nullable Decode.bool) Nothing
        |> optional "hostname" (Decode.nullable Decode.string) Nothing
        |> optional "imagePullSecrets" (Decode.nullable (Decode.list ioK8sApiCoreV1LocalObjectReferenceDecoder)) Nothing
        |> optional "initContainers" (Decode.nullable (Decode.list ioK8sApiCoreV1ContainerDecoder)) Nothing
        |> optional "nodeName" (Decode.nullable Decode.string) Nothing
        |> optional "nodeSelector" (Decode.nullable (Decode.list Decode.string)) Nothing
        |> optional "priority" (Decode.nullable Decode.int) Nothing
        |> optional "priorityClassName" (Decode.nullable Decode.string) Nothing
        |> optional "readinessGates" (Decode.nullable (Decode.list ioK8sApiCoreV1PodReadinessGateDecoder)) Nothing
        |> optional "restartPolicy" (Decode.nullable Decode.string) Nothing
        |> optional "runtimeClassName" (Decode.nullable Decode.string) Nothing
        |> optional "schedulerName" (Decode.nullable Decode.string) Nothing
        |> optional "securityContext" (Decode.nullable ioK8sApiCoreV1PodSecurityContextDecoder) Nothing
        |> optional "serviceAccount" (Decode.nullable Decode.string) Nothing
        |> optional "serviceAccountName" (Decode.nullable Decode.string) Nothing
        |> optional "shareProcessNamespace" (Decode.nullable Decode.bool) Nothing
        |> optional "subdomain" (Decode.nullable Decode.string) Nothing
        |> optional "terminationGracePeriodSeconds" (Decode.nullable Decode.int) Nothing
        |> optional "tolerations" (Decode.nullable (Decode.list ioK8sApiCoreV1TolerationDecoder)) Nothing
        |> optional "volumes" (Decode.nullable (Decode.list ioK8sApiCoreV1VolumeDecoder)) Nothing



ioK8sApiCoreV1PodSpecEncoder : IoK8sApiCoreV1PodSpec -> Encode.Value
ioK8sApiCoreV1PodSpecEncoder model =
    Encode.object
        [ ( "activeDeadlineSeconds", withDefault Encode.null (map Encode.int model.activeDeadlineSeconds) )
        , ( "affinity", withDefault Encode.null (map ioK8sApiCoreV1AffinityEncoder model.affinity) )
        , ( "automountServiceAccountToken", withDefault Encode.null (map Encode.bool model.automountServiceAccountToken) )
        , ( "containers", (Encode.list << List.map ioK8sApiCoreV1ContainerEncoder) model.containers )
        , ( "dnsConfig", withDefault Encode.null (map ioK8sApiCoreV1PodDNSConfigEncoder model.dnsConfig) )
        , ( "dnsPolicy", withDefault Encode.null (map Encode.string model.dnsPolicy) )
        , ( "enableServiceLinks", withDefault Encode.null (map Encode.bool model.enableServiceLinks) )
        , ( "hostAliases", withDefault Encode.null (map (Encode.list << List.map ioK8sApiCoreV1HostAliasEncoder) model.hostAliases) )
        , ( "hostIPC", withDefault Encode.null (map Encode.bool model.hostIPC) )
        , ( "hostNetwork", withDefault Encode.null (map Encode.bool model.hostNetwork) )
        , ( "hostPID", withDefault Encode.null (map Encode.bool model.hostPID) )
        , ( "hostname", withDefault Encode.null (map Encode.string model.hostname) )
        , ( "imagePullSecrets", withDefault Encode.null (map (Encode.list << List.map ioK8sApiCoreV1LocalObjectReferenceEncoder) model.imagePullSecrets) )
        , ( "initContainers", withDefault Encode.null (map (Encode.list << List.map ioK8sApiCoreV1ContainerEncoder) model.initContainers) )
        , ( "nodeName", withDefault Encode.null (map Encode.string model.nodeName) )
        , ( "nodeSelector", withDefault Encode.null (map (Encode.list << List.map Encode.string) model.nodeSelector) )
        , ( "priority", withDefault Encode.null (map Encode.int model.priority) )
        , ( "priorityClassName", withDefault Encode.null (map Encode.string model.priorityClassName) )
        , ( "readinessGates", withDefault Encode.null (map (Encode.list << List.map ioK8sApiCoreV1PodReadinessGateEncoder) model.readinessGates) )
        , ( "restartPolicy", withDefault Encode.null (map Encode.string model.restartPolicy) )
        , ( "runtimeClassName", withDefault Encode.null (map Encode.string model.runtimeClassName) )
        , ( "schedulerName", withDefault Encode.null (map Encode.string model.schedulerName) )
        , ( "securityContext", withDefault Encode.null (map ioK8sApiCoreV1PodSecurityContextEncoder model.securityContext) )
        , ( "serviceAccount", withDefault Encode.null (map Encode.string model.serviceAccount) )
        , ( "serviceAccountName", withDefault Encode.null (map Encode.string model.serviceAccountName) )
        , ( "shareProcessNamespace", withDefault Encode.null (map Encode.bool model.shareProcessNamespace) )
        , ( "subdomain", withDefault Encode.null (map Encode.string model.subdomain) )
        , ( "terminationGracePeriodSeconds", withDefault Encode.null (map Encode.int model.terminationGracePeriodSeconds) )
        , ( "tolerations", withDefault Encode.null (map (Encode.list << List.map ioK8sApiCoreV1TolerationEncoder) model.tolerations) )
        , ( "volumes", withDefault Encode.null (map (Encode.list << List.map ioK8sApiCoreV1VolumeEncoder) model.volumes) )
        ]


