{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiCoreV1ContainerImage exposing (IoK8sApiCoreV1ContainerImage, ioK8sApiCoreV1ContainerImageDecoder, ioK8sApiCoreV1ContainerImageEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   Describe a container image
-}


type alias IoK8sApiCoreV1ContainerImage =
    { names : (List String)
    , sizeBytes : Maybe Int
    }


ioK8sApiCoreV1ContainerImageDecoder : Decoder IoK8sApiCoreV1ContainerImage
ioK8sApiCoreV1ContainerImageDecoder =
    decode IoK8sApiCoreV1ContainerImage
        |> required "names" (Decode.list Decode.string)
        |> optional "sizeBytes" (Decode.nullable Decode.int) Nothing



ioK8sApiCoreV1ContainerImageEncoder : IoK8sApiCoreV1ContainerImage -> Encode.Value
ioK8sApiCoreV1ContainerImageEncoder model =
    Encode.object
        [ ( "names", (Encode.list << List.map Encode.string) model.names )
        , ( "sizeBytes", withDefault Encode.null (map Encode.int model.sizeBytes) )
        ]


