{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiExtensionsV1beta1RollingUpdateDaemonSet exposing (IoK8sApiExtensionsV1beta1RollingUpdateDaemonSet, ioK8sApiExtensionsV1beta1RollingUpdateDaemonSetDecoder, ioK8sApiExtensionsV1beta1RollingUpdateDaemonSetEncoder)

import Data.IoK8sApimachineryPkgUtilIntstrIntOrString exposing (IoK8sApimachineryPkgUtilIntstrIntOrString, ioK8sApimachineryPkgUtilIntstrIntOrStringDecoder, ioK8sApimachineryPkgUtilIntstrIntOrStringEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   Spec to control the desired behavior of daemon set rolling update.
-}


type alias IoK8sApiExtensionsV1beta1RollingUpdateDaemonSet =
    { maxUnavailable : Maybe IoK8sApimachineryPkgUtilIntstrIntOrString
    }


ioK8sApiExtensionsV1beta1RollingUpdateDaemonSetDecoder : Decoder IoK8sApiExtensionsV1beta1RollingUpdateDaemonSet
ioK8sApiExtensionsV1beta1RollingUpdateDaemonSetDecoder =
    decode IoK8sApiExtensionsV1beta1RollingUpdateDaemonSet
        |> optional "maxUnavailable" (Decode.nullable ioK8sApimachineryPkgUtilIntstrIntOrStringDecoder) Nothing



ioK8sApiExtensionsV1beta1RollingUpdateDaemonSetEncoder : IoK8sApiExtensionsV1beta1RollingUpdateDaemonSet -> Encode.Value
ioK8sApiExtensionsV1beta1RollingUpdateDaemonSetEncoder model =
    Encode.object
        [ ( "maxUnavailable", withDefault Encode.null (map ioK8sApimachineryPkgUtilIntstrIntOrStringEncoder model.maxUnavailable) )
        ]


