{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sKubernetesPkgApisAuthenticationV1beta1TokenReviewSpec exposing (IoK8sKubernetesPkgApisAuthenticationV1beta1TokenReviewSpec, ioK8sKubernetesPkgApisAuthenticationV1beta1TokenReviewSpecDecoder, ioK8sKubernetesPkgApisAuthenticationV1beta1TokenReviewSpecEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)




type alias IoK8sKubernetesPkgApisAuthenticationV1beta1TokenReviewSpec =
    {     }


ioK8sKubernetesPkgApisAuthenticationV1beta1TokenReviewSpecDecoder : Decoder IoK8sKubernetesPkgApisAuthenticationV1beta1TokenReviewSpec
ioK8sKubernetesPkgApisAuthenticationV1beta1TokenReviewSpecDecoder =
    decode IoK8sKubernetesPkgApisAuthenticationV1beta1TokenReviewSpec



ioK8sKubernetesPkgApisAuthenticationV1beta1TokenReviewSpecEncoder : IoK8sKubernetesPkgApisAuthenticationV1beta1TokenReviewSpec -> Encode.Value
ioK8sKubernetesPkgApisAuthenticationV1beta1TokenReviewSpecEncoder model =
    Encode.object
        ]


