{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiAuthorizationV1beta1SubjectAccessReviewSpec exposing (IoK8sApiAuthorizationV1beta1SubjectAccessReviewSpec, ioK8sApiAuthorizationV1beta1SubjectAccessReviewSpecDecoder, ioK8sApiAuthorizationV1beta1SubjectAccessReviewSpecEncoder)

import Data.List exposing (List, stringDecoder, stringEncoder)
import Data.IoK8sApiAuthorizationV1beta1NonResourceAttributes exposing (IoK8sApiAuthorizationV1beta1NonResourceAttributes, ioK8sApiAuthorizationV1beta1NonResourceAttributesDecoder, ioK8sApiAuthorizationV1beta1NonResourceAttributesEncoder)
import Data.IoK8sApiAuthorizationV1beta1ResourceAttributes exposing (IoK8sApiAuthorizationV1beta1ResourceAttributes, ioK8sApiAuthorizationV1beta1ResourceAttributesDecoder, ioK8sApiAuthorizationV1beta1ResourceAttributesEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   SubjectAccessReviewSpec is a description of the access request.  Exactly one of ResourceAuthorizationAttributes and NonResourceAuthorizationAttributes must be set
-}


type alias IoK8sApiAuthorizationV1beta1SubjectAccessReviewSpec =
    { extra : Maybe (List String)
    , group : Maybe (List String)
    , nonResourceAttributes : Maybe IoK8sApiAuthorizationV1beta1NonResourceAttributes
    , resourceAttributes : Maybe IoK8sApiAuthorizationV1beta1ResourceAttributes
    , uid : Maybe String
    , user : Maybe String
    }


ioK8sApiAuthorizationV1beta1SubjectAccessReviewSpecDecoder : Decoder IoK8sApiAuthorizationV1beta1SubjectAccessReviewSpec
ioK8sApiAuthorizationV1beta1SubjectAccessReviewSpecDecoder =
    decode IoK8sApiAuthorizationV1beta1SubjectAccessReviewSpec
        |> optional "extra" (Decode.nullable (Decode.list stringDecoder)) Nothing
        |> optional "group" (Decode.nullable (Decode.list Decode.string)) Nothing
        |> optional "nonResourceAttributes" (Decode.nullable ioK8sApiAuthorizationV1beta1NonResourceAttributesDecoder) Nothing
        |> optional "resourceAttributes" (Decode.nullable ioK8sApiAuthorizationV1beta1ResourceAttributesDecoder) Nothing
        |> optional "uid" (Decode.nullable Decode.string) Nothing
        |> optional "user" (Decode.nullable Decode.string) Nothing



ioK8sApiAuthorizationV1beta1SubjectAccessReviewSpecEncoder : IoK8sApiAuthorizationV1beta1SubjectAccessReviewSpec -> Encode.Value
ioK8sApiAuthorizationV1beta1SubjectAccessReviewSpecEncoder model =
    Encode.object
        [ ( "extra", withDefault Encode.null (map (Encode.list << List.map stringEncoder) model.extra) )
        , ( "group", withDefault Encode.null (map (Encode.list << List.map Encode.string) model.group) )
        , ( "nonResourceAttributes", withDefault Encode.null (map ioK8sApiAuthorizationV1beta1NonResourceAttributesEncoder model.nonResourceAttributes) )
        , ( "resourceAttributes", withDefault Encode.null (map ioK8sApiAuthorizationV1beta1ResourceAttributesEncoder model.resourceAttributes) )
        , ( "uid", withDefault Encode.null (map Encode.string model.uid) )
        , ( "user", withDefault Encode.null (map Encode.string model.user) )
        ]


