{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiCoreV1HostAlias exposing (IoK8sApiCoreV1HostAlias, ioK8sApiCoreV1HostAliasDecoder, ioK8sApiCoreV1HostAliasEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   HostAlias holds the mapping between IP and hostnames that will be injected as an entry in the pod's hosts file.
-}


type alias IoK8sApiCoreV1HostAlias =
    { hostnames : Maybe (List String)
    , ip : Maybe String
    }


ioK8sApiCoreV1HostAliasDecoder : Decoder IoK8sApiCoreV1HostAlias
ioK8sApiCoreV1HostAliasDecoder =
    decode IoK8sApiCoreV1HostAlias
        |> optional "hostnames" (Decode.nullable (Decode.list Decode.string)) Nothing
        |> optional "ip" (Decode.nullable Decode.string) Nothing



ioK8sApiCoreV1HostAliasEncoder : IoK8sApiCoreV1HostAlias -> Encode.Value
ioK8sApiCoreV1HostAliasEncoder model =
    Encode.object
        [ ( "hostnames", withDefault Encode.null (map (Encode.list << List.map Encode.string) model.hostnames) )
        , ( "ip", withDefault Encode.null (map Encode.string model.ip) )
        ]


