{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sKubernetesPkgApisRbacV1beta1Subject exposing (IoK8sKubernetesPkgApisRbacV1beta1Subject, ioK8sKubernetesPkgApisRbacV1beta1SubjectDecoder, ioK8sKubernetesPkgApisRbacV1beta1SubjectEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)




type alias IoK8sKubernetesPkgApisRbacV1beta1Subject =
    {     }


ioK8sKubernetesPkgApisRbacV1beta1SubjectDecoder : Decoder IoK8sKubernetesPkgApisRbacV1beta1Subject
ioK8sKubernetesPkgApisRbacV1beta1SubjectDecoder =
    decode IoK8sKubernetesPkgApisRbacV1beta1Subject



ioK8sKubernetesPkgApisRbacV1beta1SubjectEncoder : IoK8sKubernetesPkgApisRbacV1beta1Subject -> Encode.Value
ioK8sKubernetesPkgApisRbacV1beta1SubjectEncoder model =
    Encode.object
        ]


