{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiAutoscalingV2beta2CrossVersionObjectReference exposing (IoK8sApiAutoscalingV2beta2CrossVersionObjectReference, ioK8sApiAutoscalingV2beta2CrossVersionObjectReferenceDecoder, ioK8sApiAutoscalingV2beta2CrossVersionObjectReferenceEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   CrossVersionObjectReference contains enough information to let you identify the referred resource.
-}


type alias IoK8sApiAutoscalingV2beta2CrossVersionObjectReference =
    { apiVersion : Maybe String
    , kind : String
    , name : String
    }


ioK8sApiAutoscalingV2beta2CrossVersionObjectReferenceDecoder : Decoder IoK8sApiAutoscalingV2beta2CrossVersionObjectReference
ioK8sApiAutoscalingV2beta2CrossVersionObjectReferenceDecoder =
    decode IoK8sApiAutoscalingV2beta2CrossVersionObjectReference
        |> optional "apiVersion" (Decode.nullable Decode.string) Nothing
        |> required "kind" Decode.string
        |> required "name" Decode.string



ioK8sApiAutoscalingV2beta2CrossVersionObjectReferenceEncoder : IoK8sApiAutoscalingV2beta2CrossVersionObjectReference -> Encode.Value
ioK8sApiAutoscalingV2beta2CrossVersionObjectReferenceEncoder model =
    Encode.object
        [ ( "apiVersion", withDefault Encode.null (map Encode.string model.apiVersion) )
        , ( "kind", Encode.string model.kind )
        , ( "name", Encode.string model.name )
        ]


