{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApimachineryPkgVersionInfo exposing (IoK8sApimachineryPkgVersionInfo, ioK8sApimachineryPkgVersionInfoDecoder, ioK8sApimachineryPkgVersionInfoEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   Info contains versioning information. how we'll want to distribute that information.
-}


type alias IoK8sApimachineryPkgVersionInfo =
    { buildDate : String
    , compiler : String
    , gitCommit : String
    , gitTreeState : String
    , gitVersion : String
    , goVersion : String
    , major : String
    , minor : String
    , platform : String
    }


ioK8sApimachineryPkgVersionInfoDecoder : Decoder IoK8sApimachineryPkgVersionInfo
ioK8sApimachineryPkgVersionInfoDecoder =
    decode IoK8sApimachineryPkgVersionInfo
        |> required "buildDate" Decode.string
        |> required "compiler" Decode.string
        |> required "gitCommit" Decode.string
        |> required "gitTreeState" Decode.string
        |> required "gitVersion" Decode.string
        |> required "goVersion" Decode.string
        |> required "major" Decode.string
        |> required "minor" Decode.string
        |> required "platform" Decode.string



ioK8sApimachineryPkgVersionInfoEncoder : IoK8sApimachineryPkgVersionInfo -> Encode.Value
ioK8sApimachineryPkgVersionInfoEncoder model =
    Encode.object
        [ ( "buildDate", Encode.string model.buildDate )
        , ( "compiler", Encode.string model.compiler )
        , ( "gitCommit", Encode.string model.gitCommit )
        , ( "gitTreeState", Encode.string model.gitTreeState )
        , ( "gitVersion", Encode.string model.gitVersion )
        , ( "goVersion", Encode.string model.goVersion )
        , ( "major", Encode.string model.major )
        , ( "minor", Encode.string model.minor )
        , ( "platform", Encode.string model.platform )
        ]


