{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiPolicyV1beta1PodSecurityPolicyList exposing (IoK8sApiPolicyV1beta1PodSecurityPolicyList, ioK8sApiPolicyV1beta1PodSecurityPolicyListDecoder, ioK8sApiPolicyV1beta1PodSecurityPolicyListEncoder)

import Data.IoK8sApiPolicyV1beta1PodSecurityPolicy exposing (IoK8sApiPolicyV1beta1PodSecurityPolicy, ioK8sApiPolicyV1beta1PodSecurityPolicyDecoder, ioK8sApiPolicyV1beta1PodSecurityPolicyEncoder)
import Data.IoK8sApimachineryPkgApisMetaV1ListMeta exposing (IoK8sApimachineryPkgApisMetaV1ListMeta, ioK8sApimachineryPkgApisMetaV1ListMetaDecoder, ioK8sApimachineryPkgApisMetaV1ListMetaEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   PodSecurityPolicyList is a list of PodSecurityPolicy objects.
-}


type alias IoK8sApiPolicyV1beta1PodSecurityPolicyList =
    { apiVersion : Maybe String
    , items : (List IoK8sApiPolicyV1beta1PodSecurityPolicy)
    , kind : Maybe String
    , metadata : Maybe IoK8sApimachineryPkgApisMetaV1ListMeta
    }


ioK8sApiPolicyV1beta1PodSecurityPolicyListDecoder : Decoder IoK8sApiPolicyV1beta1PodSecurityPolicyList
ioK8sApiPolicyV1beta1PodSecurityPolicyListDecoder =
    decode IoK8sApiPolicyV1beta1PodSecurityPolicyList
        |> optional "apiVersion" (Decode.nullable Decode.string) Nothing
        |> required "items" (Decode.list ioK8sApiPolicyV1beta1PodSecurityPolicyDecoder)
        |> optional "kind" (Decode.nullable Decode.string) Nothing
        |> optional "metadata" (Decode.nullable ioK8sApimachineryPkgApisMetaV1ListMetaDecoder) Nothing



ioK8sApiPolicyV1beta1PodSecurityPolicyListEncoder : IoK8sApiPolicyV1beta1PodSecurityPolicyList -> Encode.Value
ioK8sApiPolicyV1beta1PodSecurityPolicyListEncoder model =
    Encode.object
        [ ( "apiVersion", withDefault Encode.null (map Encode.string model.apiVersion) )
        , ( "items", (Encode.list << List.map ioK8sApiPolicyV1beta1PodSecurityPolicyEncoder) model.items )
        , ( "kind", withDefault Encode.null (map Encode.string model.kind) )
        , ( "metadata", withDefault Encode.null (map ioK8sApimachineryPkgApisMetaV1ListMetaEncoder model.metadata) )
        ]


