{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sKubernetesPkgApiV1GitRepoVolumeSource exposing (IoK8sKubernetesPkgApiV1GitRepoVolumeSource, ioK8sKubernetesPkgApiV1GitRepoVolumeSourceDecoder, ioK8sKubernetesPkgApiV1GitRepoVolumeSourceEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)




type alias IoK8sKubernetesPkgApiV1GitRepoVolumeSource =
    {     }


ioK8sKubernetesPkgApiV1GitRepoVolumeSourceDecoder : Decoder IoK8sKubernetesPkgApiV1GitRepoVolumeSource
ioK8sKubernetesPkgApiV1GitRepoVolumeSourceDecoder =
    decode IoK8sKubernetesPkgApiV1GitRepoVolumeSource



ioK8sKubernetesPkgApiV1GitRepoVolumeSourceEncoder : IoK8sKubernetesPkgApiV1GitRepoVolumeSource -> Encode.Value
ioK8sKubernetesPkgApiV1GitRepoVolumeSourceEncoder model =
    Encode.object
        ]


