{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiAutoscalingV2beta2MetricValueStatus exposing (IoK8sApiAutoscalingV2beta2MetricValueStatus, ioK8sApiAutoscalingV2beta2MetricValueStatusDecoder, ioK8sApiAutoscalingV2beta2MetricValueStatusEncoder)

import Data.IoK8sApimachineryPkgApiResourceQuantity exposing (IoK8sApimachineryPkgApiResourceQuantity, ioK8sApimachineryPkgApiResourceQuantityDecoder, ioK8sApimachineryPkgApiResourceQuantityEncoder)
import Data.IoK8sApimachineryPkgApiResourceQuantity exposing (IoK8sApimachineryPkgApiResourceQuantity, ioK8sApimachineryPkgApiResourceQuantityDecoder, ioK8sApimachineryPkgApiResourceQuantityEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   MetricValueStatus holds the current value for a metric
-}


type alias IoK8sApiAutoscalingV2beta2MetricValueStatus =
    { averageUtilization : Maybe Int
    , averageValue : Maybe IoK8sApimachineryPkgApiResourceQuantity
    , value : Maybe IoK8sApimachineryPkgApiResourceQuantity
    }


ioK8sApiAutoscalingV2beta2MetricValueStatusDecoder : Decoder IoK8sApiAutoscalingV2beta2MetricValueStatus
ioK8sApiAutoscalingV2beta2MetricValueStatusDecoder =
    decode IoK8sApiAutoscalingV2beta2MetricValueStatus
        |> optional "averageUtilization" (Decode.nullable Decode.int) Nothing
        |> optional "averageValue" (Decode.nullable ioK8sApimachineryPkgApiResourceQuantityDecoder) Nothing
        |> optional "value" (Decode.nullable ioK8sApimachineryPkgApiResourceQuantityDecoder) Nothing



ioK8sApiAutoscalingV2beta2MetricValueStatusEncoder : IoK8sApiAutoscalingV2beta2MetricValueStatus -> Encode.Value
ioK8sApiAutoscalingV2beta2MetricValueStatusEncoder model =
    Encode.object
        [ ( "averageUtilization", withDefault Encode.null (map Encode.int model.averageUtilization) )
        , ( "averageValue", withDefault Encode.null (map ioK8sApimachineryPkgApiResourceQuantityEncoder model.averageValue) )
        , ( "value", withDefault Encode.null (map ioK8sApimachineryPkgApiResourceQuantityEncoder model.value) )
        ]


