{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiAppsV1StatefulSetStatus exposing (IoK8sApiAppsV1StatefulSetStatus, ioK8sApiAppsV1StatefulSetStatusDecoder, ioK8sApiAppsV1StatefulSetStatusEncoder)

import Data.IoK8sApiAppsV1StatefulSetCondition exposing (IoK8sApiAppsV1StatefulSetCondition, ioK8sApiAppsV1StatefulSetConditionDecoder, ioK8sApiAppsV1StatefulSetConditionEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   StatefulSetStatus represents the current state of a StatefulSet.
-}


type alias IoK8sApiAppsV1StatefulSetStatus =
    { collisionCount : Maybe Int
    , conditions : Maybe (List IoK8sApiAppsV1StatefulSetCondition)
    , currentReplicas : Maybe Int
    , currentRevision : Maybe String
    , observedGeneration : Maybe Int
    , readyReplicas : Maybe Int
    , replicas : Int
    , updateRevision : Maybe String
    , updatedReplicas : Maybe Int
    }


ioK8sApiAppsV1StatefulSetStatusDecoder : Decoder IoK8sApiAppsV1StatefulSetStatus
ioK8sApiAppsV1StatefulSetStatusDecoder =
    decode IoK8sApiAppsV1StatefulSetStatus
        |> optional "collisionCount" (Decode.nullable Decode.int) Nothing
        |> optional "conditions" (Decode.nullable (Decode.list ioK8sApiAppsV1StatefulSetConditionDecoder)) Nothing
        |> optional "currentReplicas" (Decode.nullable Decode.int) Nothing
        |> optional "currentRevision" (Decode.nullable Decode.string) Nothing
        |> optional "observedGeneration" (Decode.nullable Decode.int) Nothing
        |> optional "readyReplicas" (Decode.nullable Decode.int) Nothing
        |> required "replicas" Decode.int
        |> optional "updateRevision" (Decode.nullable Decode.string) Nothing
        |> optional "updatedReplicas" (Decode.nullable Decode.int) Nothing



ioK8sApiAppsV1StatefulSetStatusEncoder : IoK8sApiAppsV1StatefulSetStatus -> Encode.Value
ioK8sApiAppsV1StatefulSetStatusEncoder model =
    Encode.object
        [ ( "collisionCount", withDefault Encode.null (map Encode.int model.collisionCount) )
        , ( "conditions", withDefault Encode.null (map (Encode.list << List.map ioK8sApiAppsV1StatefulSetConditionEncoder) model.conditions) )
        , ( "currentReplicas", withDefault Encode.null (map Encode.int model.currentReplicas) )
        , ( "currentRevision", withDefault Encode.null (map Encode.string model.currentRevision) )
        , ( "observedGeneration", withDefault Encode.null (map Encode.int model.observedGeneration) )
        , ( "readyReplicas", withDefault Encode.null (map Encode.int model.readyReplicas) )
        , ( "replicas", Encode.int model.replicas )
        , ( "updateRevision", withDefault Encode.null (map Encode.string model.updateRevision) )
        , ( "updatedReplicas", withDefault Encode.null (map Encode.int model.updatedReplicas) )
        ]


