{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiCoreV1ResourceFieldSelector exposing (IoK8sApiCoreV1ResourceFieldSelector, ioK8sApiCoreV1ResourceFieldSelectorDecoder, ioK8sApiCoreV1ResourceFieldSelectorEncoder)

import Data.IoK8sApimachineryPkgApiResourceQuantity exposing (IoK8sApimachineryPkgApiResourceQuantity, ioK8sApimachineryPkgApiResourceQuantityDecoder, ioK8sApimachineryPkgApiResourceQuantityEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   ResourceFieldSelector represents container resources (cpu, memory) and their output format
-}


type alias IoK8sApiCoreV1ResourceFieldSelector =
    { containerName : Maybe String
    , divisor : Maybe IoK8sApimachineryPkgApiResourceQuantity
    , resource : String
    }


ioK8sApiCoreV1ResourceFieldSelectorDecoder : Decoder IoK8sApiCoreV1ResourceFieldSelector
ioK8sApiCoreV1ResourceFieldSelectorDecoder =
    decode IoK8sApiCoreV1ResourceFieldSelector
        |> optional "containerName" (Decode.nullable Decode.string) Nothing
        |> optional "divisor" (Decode.nullable ioK8sApimachineryPkgApiResourceQuantityDecoder) Nothing
        |> required "resource" Decode.string



ioK8sApiCoreV1ResourceFieldSelectorEncoder : IoK8sApiCoreV1ResourceFieldSelector -> Encode.Value
ioK8sApiCoreV1ResourceFieldSelectorEncoder model =
    Encode.object
        [ ( "containerName", withDefault Encode.null (map Encode.string model.containerName) )
        , ( "divisor", withDefault Encode.null (map ioK8sApimachineryPkgApiResourceQuantityEncoder model.divisor) )
        , ( "resource", Encode.string model.resource )
        ]


