{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiRbacV1beta1RoleBinding exposing (IoK8sApiRbacV1beta1RoleBinding, ioK8sApiRbacV1beta1RoleBindingDecoder, ioK8sApiRbacV1beta1RoleBindingEncoder)

import Data.IoK8sApimachineryPkgApisMetaV1ObjectMeta exposing (IoK8sApimachineryPkgApisMetaV1ObjectMeta, ioK8sApimachineryPkgApisMetaV1ObjectMetaDecoder, ioK8sApimachineryPkgApisMetaV1ObjectMetaEncoder)
import Data.IoK8sApiRbacV1beta1RoleRef exposing (IoK8sApiRbacV1beta1RoleRef, ioK8sApiRbacV1beta1RoleRefDecoder, ioK8sApiRbacV1beta1RoleRefEncoder)
import Data.IoK8sApiRbacV1beta1Subject exposing (IoK8sApiRbacV1beta1Subject, ioK8sApiRbacV1beta1SubjectDecoder, ioK8sApiRbacV1beta1SubjectEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   RoleBinding references a role, but does not contain it.  It can reference a Role in the same namespace or a ClusterRole in the global namespace. It adds who information via Subjects and namespace information by which namespace it exists in.  RoleBindings in a given namespace only have effect in that namespace.
-}


type alias IoK8sApiRbacV1beta1RoleBinding =
    { apiVersion : Maybe String
    , kind : Maybe String
    , metadata : Maybe IoK8sApimachineryPkgApisMetaV1ObjectMeta
    , roleRef : IoK8sApiRbacV1beta1RoleRef
    , subjects : Maybe (List IoK8sApiRbacV1beta1Subject)
    }


ioK8sApiRbacV1beta1RoleBindingDecoder : Decoder IoK8sApiRbacV1beta1RoleBinding
ioK8sApiRbacV1beta1RoleBindingDecoder =
    decode IoK8sApiRbacV1beta1RoleBinding
        |> optional "apiVersion" (Decode.nullable Decode.string) Nothing
        |> optional "kind" (Decode.nullable Decode.string) Nothing
        |> optional "metadata" (Decode.nullable ioK8sApimachineryPkgApisMetaV1ObjectMetaDecoder) Nothing
        |> required "roleRef" ioK8sApiRbacV1beta1RoleRefDecoder
        |> optional "subjects" (Decode.nullable (Decode.list ioK8sApiRbacV1beta1SubjectDecoder)) Nothing



ioK8sApiRbacV1beta1RoleBindingEncoder : IoK8sApiRbacV1beta1RoleBinding -> Encode.Value
ioK8sApiRbacV1beta1RoleBindingEncoder model =
    Encode.object
        [ ( "apiVersion", withDefault Encode.null (map Encode.string model.apiVersion) )
        , ( "kind", withDefault Encode.null (map Encode.string model.kind) )
        , ( "metadata", withDefault Encode.null (map ioK8sApimachineryPkgApisMetaV1ObjectMetaEncoder model.metadata) )
        , ( "roleRef", ioK8sApiRbacV1beta1RoleRefEncoder model.roleRef )
        , ( "subjects", withDefault Encode.null (map (Encode.list << List.map ioK8sApiRbacV1beta1SubjectEncoder) model.subjects) )
        ]


