{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiCoreV1DownwardAPIProjection exposing (IoK8sApiCoreV1DownwardAPIProjection, ioK8sApiCoreV1DownwardAPIProjectionDecoder, ioK8sApiCoreV1DownwardAPIProjectionEncoder)

import Data.IoK8sApiCoreV1DownwardAPIVolumeFile exposing (IoK8sApiCoreV1DownwardAPIVolumeFile, ioK8sApiCoreV1DownwardAPIVolumeFileDecoder, ioK8sApiCoreV1DownwardAPIVolumeFileEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   Represents downward API info for projecting into a projected volume. Note that this is identical to a downwardAPI volume source without the default mode.
-}


type alias IoK8sApiCoreV1DownwardAPIProjection =
    { items : Maybe (List IoK8sApiCoreV1DownwardAPIVolumeFile)
    }


ioK8sApiCoreV1DownwardAPIProjectionDecoder : Decoder IoK8sApiCoreV1DownwardAPIProjection
ioK8sApiCoreV1DownwardAPIProjectionDecoder =
    decode IoK8sApiCoreV1DownwardAPIProjection
        |> optional "items" (Decode.nullable (Decode.list ioK8sApiCoreV1DownwardAPIVolumeFileDecoder)) Nothing



ioK8sApiCoreV1DownwardAPIProjectionEncoder : IoK8sApiCoreV1DownwardAPIProjection -> Encode.Value
ioK8sApiCoreV1DownwardAPIProjectionEncoder model =
    Encode.object
        [ ( "items", withDefault Encode.null (map (Encode.list << List.map ioK8sApiCoreV1DownwardAPIVolumeFileEncoder) model.items) )
        ]


