{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiAuditregistrationV1alpha1AuditSinkSpec exposing (IoK8sApiAuditregistrationV1alpha1AuditSinkSpec, ioK8sApiAuditregistrationV1alpha1AuditSinkSpecDecoder, ioK8sApiAuditregistrationV1alpha1AuditSinkSpecEncoder)

import Data.IoK8sApiAuditregistrationV1alpha1Policy exposing (IoK8sApiAuditregistrationV1alpha1Policy, ioK8sApiAuditregistrationV1alpha1PolicyDecoder, ioK8sApiAuditregistrationV1alpha1PolicyEncoder)
import Data.IoK8sApiAuditregistrationV1alpha1Webhook exposing (IoK8sApiAuditregistrationV1alpha1Webhook, ioK8sApiAuditregistrationV1alpha1WebhookDecoder, ioK8sApiAuditregistrationV1alpha1WebhookEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   AuditSinkSpec holds the spec for the audit sink
-}


type alias IoK8sApiAuditregistrationV1alpha1AuditSinkSpec =
    { policy : IoK8sApiAuditregistrationV1alpha1Policy
    , webhook : IoK8sApiAuditregistrationV1alpha1Webhook
    }


ioK8sApiAuditregistrationV1alpha1AuditSinkSpecDecoder : Decoder IoK8sApiAuditregistrationV1alpha1AuditSinkSpec
ioK8sApiAuditregistrationV1alpha1AuditSinkSpecDecoder =
    decode IoK8sApiAuditregistrationV1alpha1AuditSinkSpec
        |> required "policy" ioK8sApiAuditregistrationV1alpha1PolicyDecoder
        |> required "webhook" ioK8sApiAuditregistrationV1alpha1WebhookDecoder



ioK8sApiAuditregistrationV1alpha1AuditSinkSpecEncoder : IoK8sApiAuditregistrationV1alpha1AuditSinkSpec -> Encode.Value
ioK8sApiAuditregistrationV1alpha1AuditSinkSpecEncoder model =
    Encode.object
        [ ( "policy", ioK8sApiAuditregistrationV1alpha1PolicyEncoder model.policy )
        , ( "webhook", ioK8sApiAuditregistrationV1alpha1WebhookEncoder model.webhook )
        ]


