{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiCoreV1Container exposing (IoK8sApiCoreV1Container, ioK8sApiCoreV1ContainerDecoder, ioK8sApiCoreV1ContainerEncoder)

import Data.IoK8sApiCoreV1EnvVar exposing (IoK8sApiCoreV1EnvVar, ioK8sApiCoreV1EnvVarDecoder, ioK8sApiCoreV1EnvVarEncoder)
import Data.IoK8sApiCoreV1EnvFromSource exposing (IoK8sApiCoreV1EnvFromSource, ioK8sApiCoreV1EnvFromSourceDecoder, ioK8sApiCoreV1EnvFromSourceEncoder)
import Data.IoK8sApiCoreV1Lifecycle exposing (IoK8sApiCoreV1Lifecycle, ioK8sApiCoreV1LifecycleDecoder, ioK8sApiCoreV1LifecycleEncoder)
import Data.IoK8sApiCoreV1Probe exposing (IoK8sApiCoreV1Probe, ioK8sApiCoreV1ProbeDecoder, ioK8sApiCoreV1ProbeEncoder)
import Data.IoK8sApiCoreV1ContainerPort exposing (IoK8sApiCoreV1ContainerPort, ioK8sApiCoreV1ContainerPortDecoder, ioK8sApiCoreV1ContainerPortEncoder)
import Data.IoK8sApiCoreV1Probe exposing (IoK8sApiCoreV1Probe, ioK8sApiCoreV1ProbeDecoder, ioK8sApiCoreV1ProbeEncoder)
import Data.IoK8sApiCoreV1ResourceRequirements exposing (IoK8sApiCoreV1ResourceRequirements, ioK8sApiCoreV1ResourceRequirementsDecoder, ioK8sApiCoreV1ResourceRequirementsEncoder)
import Data.IoK8sApiCoreV1SecurityContext exposing (IoK8sApiCoreV1SecurityContext, ioK8sApiCoreV1SecurityContextDecoder, ioK8sApiCoreV1SecurityContextEncoder)
import Data.IoK8sApiCoreV1VolumeDevice exposing (IoK8sApiCoreV1VolumeDevice, ioK8sApiCoreV1VolumeDeviceDecoder, ioK8sApiCoreV1VolumeDeviceEncoder)
import Data.IoK8sApiCoreV1VolumeMount exposing (IoK8sApiCoreV1VolumeMount, ioK8sApiCoreV1VolumeMountDecoder, ioK8sApiCoreV1VolumeMountEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   A single application container that you want to run within a pod.
-}


type alias IoK8sApiCoreV1Container =
    { args : Maybe (List String)
    , command : Maybe (List String)
    , env : Maybe (List IoK8sApiCoreV1EnvVar)
    , envFrom : Maybe (List IoK8sApiCoreV1EnvFromSource)
    , image : Maybe String
    , imagePullPolicy : Maybe String
    , lifecycle : Maybe IoK8sApiCoreV1Lifecycle
    , livenessProbe : Maybe IoK8sApiCoreV1Probe
    , name : String
    , ports : Maybe (List IoK8sApiCoreV1ContainerPort)
    , readinessProbe : Maybe IoK8sApiCoreV1Probe
    , resources : Maybe IoK8sApiCoreV1ResourceRequirements
    , securityContext : Maybe IoK8sApiCoreV1SecurityContext
    , stdin : Maybe Bool
    , stdinOnce : Maybe Bool
    , terminationMessagePath : Maybe String
    , terminationMessagePolicy : Maybe String
    , tty : Maybe Bool
    , volumeDevices : Maybe (List IoK8sApiCoreV1VolumeDevice)
    , volumeMounts : Maybe (List IoK8sApiCoreV1VolumeMount)
    , workingDir : Maybe String
    }


ioK8sApiCoreV1ContainerDecoder : Decoder IoK8sApiCoreV1Container
ioK8sApiCoreV1ContainerDecoder =
    decode IoK8sApiCoreV1Container
        |> optional "args" (Decode.nullable (Decode.list Decode.string)) Nothing
        |> optional "command" (Decode.nullable (Decode.list Decode.string)) Nothing
        |> optional "env" (Decode.nullable (Decode.list ioK8sApiCoreV1EnvVarDecoder)) Nothing
        |> optional "envFrom" (Decode.nullable (Decode.list ioK8sApiCoreV1EnvFromSourceDecoder)) Nothing
        |> optional "image" (Decode.nullable Decode.string) Nothing
        |> optional "imagePullPolicy" (Decode.nullable Decode.string) Nothing
        |> optional "lifecycle" (Decode.nullable ioK8sApiCoreV1LifecycleDecoder) Nothing
        |> optional "livenessProbe" (Decode.nullable ioK8sApiCoreV1ProbeDecoder) Nothing
        |> required "name" Decode.string
        |> optional "ports" (Decode.nullable (Decode.list ioK8sApiCoreV1ContainerPortDecoder)) Nothing
        |> optional "readinessProbe" (Decode.nullable ioK8sApiCoreV1ProbeDecoder) Nothing
        |> optional "resources" (Decode.nullable ioK8sApiCoreV1ResourceRequirementsDecoder) Nothing
        |> optional "securityContext" (Decode.nullable ioK8sApiCoreV1SecurityContextDecoder) Nothing
        |> optional "stdin" (Decode.nullable Decode.bool) Nothing
        |> optional "stdinOnce" (Decode.nullable Decode.bool) Nothing
        |> optional "terminationMessagePath" (Decode.nullable Decode.string) Nothing
        |> optional "terminationMessagePolicy" (Decode.nullable Decode.string) Nothing
        |> optional "tty" (Decode.nullable Decode.bool) Nothing
        |> optional "volumeDevices" (Decode.nullable (Decode.list ioK8sApiCoreV1VolumeDeviceDecoder)) Nothing
        |> optional "volumeMounts" (Decode.nullable (Decode.list ioK8sApiCoreV1VolumeMountDecoder)) Nothing
        |> optional "workingDir" (Decode.nullable Decode.string) Nothing



ioK8sApiCoreV1ContainerEncoder : IoK8sApiCoreV1Container -> Encode.Value
ioK8sApiCoreV1ContainerEncoder model =
    Encode.object
        [ ( "args", withDefault Encode.null (map (Encode.list << List.map Encode.string) model.args) )
        , ( "command", withDefault Encode.null (map (Encode.list << List.map Encode.string) model.command) )
        , ( "env", withDefault Encode.null (map (Encode.list << List.map ioK8sApiCoreV1EnvVarEncoder) model.env) )
        , ( "envFrom", withDefault Encode.null (map (Encode.list << List.map ioK8sApiCoreV1EnvFromSourceEncoder) model.envFrom) )
        , ( "image", withDefault Encode.null (map Encode.string model.image) )
        , ( "imagePullPolicy", withDefault Encode.null (map Encode.string model.imagePullPolicy) )
        , ( "lifecycle", withDefault Encode.null (map ioK8sApiCoreV1LifecycleEncoder model.lifecycle) )
        , ( "livenessProbe", withDefault Encode.null (map ioK8sApiCoreV1ProbeEncoder model.livenessProbe) )
        , ( "name", Encode.string model.name )
        , ( "ports", withDefault Encode.null (map (Encode.list << List.map ioK8sApiCoreV1ContainerPortEncoder) model.ports) )
        , ( "readinessProbe", withDefault Encode.null (map ioK8sApiCoreV1ProbeEncoder model.readinessProbe) )
        , ( "resources", withDefault Encode.null (map ioK8sApiCoreV1ResourceRequirementsEncoder model.resources) )
        , ( "securityContext", withDefault Encode.null (map ioK8sApiCoreV1SecurityContextEncoder model.securityContext) )
        , ( "stdin", withDefault Encode.null (map Encode.bool model.stdin) )
        , ( "stdinOnce", withDefault Encode.null (map Encode.bool model.stdinOnce) )
        , ( "terminationMessagePath", withDefault Encode.null (map Encode.string model.terminationMessagePath) )
        , ( "terminationMessagePolicy", withDefault Encode.null (map Encode.string model.terminationMessagePolicy) )
        , ( "tty", withDefault Encode.null (map Encode.bool model.tty) )
        , ( "volumeDevices", withDefault Encode.null (map (Encode.list << List.map ioK8sApiCoreV1VolumeDeviceEncoder) model.volumeDevices) )
        , ( "volumeMounts", withDefault Encode.null (map (Encode.list << List.map ioK8sApiCoreV1VolumeMountEncoder) model.volumeMounts) )
        , ( "workingDir", withDefault Encode.null (map Encode.string model.workingDir) )
        ]


