{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiCoreV1ProjectedVolumeSource exposing (IoK8sApiCoreV1ProjectedVolumeSource, ioK8sApiCoreV1ProjectedVolumeSourceDecoder, ioK8sApiCoreV1ProjectedVolumeSourceEncoder)

import Data.IoK8sApiCoreV1VolumeProjection exposing (IoK8sApiCoreV1VolumeProjection, ioK8sApiCoreV1VolumeProjectionDecoder, ioK8sApiCoreV1VolumeProjectionEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   Represents a projected volume source
-}


type alias IoK8sApiCoreV1ProjectedVolumeSource =
    { defaultMode : Maybe Int
    , sources : (List IoK8sApiCoreV1VolumeProjection)
    }


ioK8sApiCoreV1ProjectedVolumeSourceDecoder : Decoder IoK8sApiCoreV1ProjectedVolumeSource
ioK8sApiCoreV1ProjectedVolumeSourceDecoder =
    decode IoK8sApiCoreV1ProjectedVolumeSource
        |> optional "defaultMode" (Decode.nullable Decode.int) Nothing
        |> required "sources" (Decode.list ioK8sApiCoreV1VolumeProjectionDecoder)



ioK8sApiCoreV1ProjectedVolumeSourceEncoder : IoK8sApiCoreV1ProjectedVolumeSource -> Encode.Value
ioK8sApiCoreV1ProjectedVolumeSourceEncoder model =
    Encode.object
        [ ( "defaultMode", withDefault Encode.null (map Encode.int model.defaultMode) )
        , ( "sources", (Encode.list << List.map ioK8sApiCoreV1VolumeProjectionEncoder) model.sources )
        ]


