{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiExtensionsV1beta1IngressStatus exposing (IoK8sApiExtensionsV1beta1IngressStatus, ioK8sApiExtensionsV1beta1IngressStatusDecoder, ioK8sApiExtensionsV1beta1IngressStatusEncoder)

import Data.IoK8sApiCoreV1LoadBalancerStatus exposing (IoK8sApiCoreV1LoadBalancerStatus, ioK8sApiCoreV1LoadBalancerStatusDecoder, ioK8sApiCoreV1LoadBalancerStatusEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   IngressStatus describe the current state of the Ingress.
-}


type alias IoK8sApiExtensionsV1beta1IngressStatus =
    { loadBalancer : Maybe IoK8sApiCoreV1LoadBalancerStatus
    }


ioK8sApiExtensionsV1beta1IngressStatusDecoder : Decoder IoK8sApiExtensionsV1beta1IngressStatus
ioK8sApiExtensionsV1beta1IngressStatusDecoder =
    decode IoK8sApiExtensionsV1beta1IngressStatus
        |> optional "loadBalancer" (Decode.nullable ioK8sApiCoreV1LoadBalancerStatusDecoder) Nothing



ioK8sApiExtensionsV1beta1IngressStatusEncoder : IoK8sApiExtensionsV1beta1IngressStatus -> Encode.Value
ioK8sApiExtensionsV1beta1IngressStatusEncoder model =
    Encode.object
        [ ( "loadBalancer", withDefault Encode.null (map ioK8sApiCoreV1LoadBalancerStatusEncoder model.loadBalancer) )
        ]


