{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiExtensionsV1beta1NetworkPolicyPeer exposing (IoK8sApiExtensionsV1beta1NetworkPolicyPeer, ioK8sApiExtensionsV1beta1NetworkPolicyPeerDecoder, ioK8sApiExtensionsV1beta1NetworkPolicyPeerEncoder)

import Data.IoK8sApiExtensionsV1beta1IPBlock exposing (IoK8sApiExtensionsV1beta1IPBlock, ioK8sApiExtensionsV1beta1IPBlockDecoder, ioK8sApiExtensionsV1beta1IPBlockEncoder)
import Data.IoK8sApimachineryPkgApisMetaV1LabelSelector exposing (IoK8sApimachineryPkgApisMetaV1LabelSelector, ioK8sApimachineryPkgApisMetaV1LabelSelectorDecoder, ioK8sApimachineryPkgApisMetaV1LabelSelectorEncoder)
import Data.IoK8sApimachineryPkgApisMetaV1LabelSelector exposing (IoK8sApimachineryPkgApisMetaV1LabelSelector, ioK8sApimachineryPkgApisMetaV1LabelSelectorDecoder, ioK8sApimachineryPkgApisMetaV1LabelSelectorEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   DEPRECATED 1.9 - This group version of NetworkPolicyPeer is deprecated by networking/v1/NetworkPolicyPeer.
-}


type alias IoK8sApiExtensionsV1beta1NetworkPolicyPeer =
    { ipBlock : Maybe IoK8sApiExtensionsV1beta1IPBlock
    , namespaceSelector : Maybe IoK8sApimachineryPkgApisMetaV1LabelSelector
    , podSelector : Maybe IoK8sApimachineryPkgApisMetaV1LabelSelector
    }


ioK8sApiExtensionsV1beta1NetworkPolicyPeerDecoder : Decoder IoK8sApiExtensionsV1beta1NetworkPolicyPeer
ioK8sApiExtensionsV1beta1NetworkPolicyPeerDecoder =
    decode IoK8sApiExtensionsV1beta1NetworkPolicyPeer
        |> optional "ipBlock" (Decode.nullable ioK8sApiExtensionsV1beta1IPBlockDecoder) Nothing
        |> optional "namespaceSelector" (Decode.nullable ioK8sApimachineryPkgApisMetaV1LabelSelectorDecoder) Nothing
        |> optional "podSelector" (Decode.nullable ioK8sApimachineryPkgApisMetaV1LabelSelectorDecoder) Nothing



ioK8sApiExtensionsV1beta1NetworkPolicyPeerEncoder : IoK8sApiExtensionsV1beta1NetworkPolicyPeer -> Encode.Value
ioK8sApiExtensionsV1beta1NetworkPolicyPeerEncoder model =
    Encode.object
        [ ( "ipBlock", withDefault Encode.null (map ioK8sApiExtensionsV1beta1IPBlockEncoder model.ipBlock) )
        , ( "namespaceSelector", withDefault Encode.null (map ioK8sApimachineryPkgApisMetaV1LabelSelectorEncoder model.namespaceSelector) )
        , ( "podSelector", withDefault Encode.null (map ioK8sApimachineryPkgApisMetaV1LabelSelectorEncoder model.podSelector) )
        ]


