{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceScale exposing (IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceScale, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceScaleDecoder, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceScaleEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   CustomResourceSubresourceScale defines how to serve the scale subresource for CustomResources.
-}


type alias IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceScale =
    { labelSelectorPath : Maybe String
    , specReplicasPath : String
    , statusReplicasPath : String
    }


ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceScaleDecoder : Decoder IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceScale
ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceScaleDecoder =
    decode IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceScale
        |> optional "labelSelectorPath" (Decode.nullable Decode.string) Nothing
        |> required "specReplicasPath" Decode.string
        |> required "statusReplicasPath" Decode.string



ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceScaleEncoder : IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceScale -> Encode.Value
ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceScaleEncoder model =
    Encode.object
        [ ( "labelSelectorPath", withDefault Encode.null (map Encode.string model.labelSelectorPath) )
        , ( "specReplicasPath", Encode.string model.specReplicasPath )
        , ( "statusReplicasPath", Encode.string model.statusReplicasPath )
        ]


