{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresources exposing (IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresources, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourcesDecoder, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourcesEncoder)

import Data.IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceScale exposing (IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceScale, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceScaleDecoder, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceScaleEncoder)
import Data.IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceStatus exposing (IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceStatus, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceStatusDecoder, ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceStatusEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   CustomResourceSubresources defines the status and scale subresources for CustomResources.
-}


type alias IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresources =
    { scale : Maybe IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceScale
    , status : Maybe IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceStatus
    }


ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourcesDecoder : Decoder IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresources
ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourcesDecoder =
    decode IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresources
        |> optional "scale" (Decode.nullable ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceScaleDecoder) Nothing
        |> optional "status" (Decode.nullable ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceStatusDecoder) Nothing



ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourcesEncoder : IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresources -> Encode.Value
ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourcesEncoder model =
    Encode.object
        [ ( "scale", withDefault Encode.null (map ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceScaleEncoder model.scale) )
        , ( "status", withDefault Encode.null (map ioK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceStatusEncoder model.status) )
        ]


