{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sKubernetesPkgApisBatchV1JobSpec exposing (IoK8sKubernetesPkgApisBatchV1JobSpec, ioK8sKubernetesPkgApisBatchV1JobSpecDecoder, ioK8sKubernetesPkgApisBatchV1JobSpecEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)




type alias IoK8sKubernetesPkgApisBatchV1JobSpec =
    {     }


ioK8sKubernetesPkgApisBatchV1JobSpecDecoder : Decoder IoK8sKubernetesPkgApisBatchV1JobSpec
ioK8sKubernetesPkgApisBatchV1JobSpecDecoder =
    decode IoK8sKubernetesPkgApisBatchV1JobSpec



ioK8sKubernetesPkgApisBatchV1JobSpecEncoder : IoK8sKubernetesPkgApisBatchV1JobSpec -> Encode.Value
ioK8sKubernetesPkgApisBatchV1JobSpecEncoder model =
    Encode.object
        ]


