{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiPolicyV1beta1HostPortRange exposing (IoK8sApiPolicyV1beta1HostPortRange, ioK8sApiPolicyV1beta1HostPortRangeDecoder, ioK8sApiPolicyV1beta1HostPortRangeEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   HostPortRange defines a range of host ports that will be enabled by a policy for pods to use.  It requires both the start and end to be defined.
-}


type alias IoK8sApiPolicyV1beta1HostPortRange =
    { max : Int
    , min : Int
    }


ioK8sApiPolicyV1beta1HostPortRangeDecoder : Decoder IoK8sApiPolicyV1beta1HostPortRange
ioK8sApiPolicyV1beta1HostPortRangeDecoder =
    decode IoK8sApiPolicyV1beta1HostPortRange
        |> required "max" Decode.int
        |> required "min" Decode.int



ioK8sApiPolicyV1beta1HostPortRangeEncoder : IoK8sApiPolicyV1beta1HostPortRange -> Encode.Value
ioK8sApiPolicyV1beta1HostPortRangeEncoder model =
    Encode.object
        [ ( "max", Encode.int model.max )
        , ( "min", Encode.int model.min )
        ]


