{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiCoreV1Namespace exposing (IoK8sApiCoreV1Namespace, ioK8sApiCoreV1NamespaceDecoder, ioK8sApiCoreV1NamespaceEncoder)

import Data.IoK8sApimachineryPkgApisMetaV1ObjectMeta exposing (IoK8sApimachineryPkgApisMetaV1ObjectMeta, ioK8sApimachineryPkgApisMetaV1ObjectMetaDecoder, ioK8sApimachineryPkgApisMetaV1ObjectMetaEncoder)
import Data.IoK8sApiCoreV1NamespaceSpec exposing (IoK8sApiCoreV1NamespaceSpec, ioK8sApiCoreV1NamespaceSpecDecoder, ioK8sApiCoreV1NamespaceSpecEncoder)
import Data.IoK8sApiCoreV1NamespaceStatus exposing (IoK8sApiCoreV1NamespaceStatus, ioK8sApiCoreV1NamespaceStatusDecoder, ioK8sApiCoreV1NamespaceStatusEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   Namespace provides a scope for Names. Use of multiple namespaces is optional.
-}


type alias IoK8sApiCoreV1Namespace =
    { apiVersion : Maybe String
    , kind : Maybe String
    , metadata : Maybe IoK8sApimachineryPkgApisMetaV1ObjectMeta
    , spec : Maybe IoK8sApiCoreV1NamespaceSpec
    , status : Maybe IoK8sApiCoreV1NamespaceStatus
    }


ioK8sApiCoreV1NamespaceDecoder : Decoder IoK8sApiCoreV1Namespace
ioK8sApiCoreV1NamespaceDecoder =
    decode IoK8sApiCoreV1Namespace
        |> optional "apiVersion" (Decode.nullable Decode.string) Nothing
        |> optional "kind" (Decode.nullable Decode.string) Nothing
        |> optional "metadata" (Decode.nullable ioK8sApimachineryPkgApisMetaV1ObjectMetaDecoder) Nothing
        |> optional "spec" (Decode.nullable ioK8sApiCoreV1NamespaceSpecDecoder) Nothing
        |> optional "status" (Decode.nullable ioK8sApiCoreV1NamespaceStatusDecoder) Nothing



ioK8sApiCoreV1NamespaceEncoder : IoK8sApiCoreV1Namespace -> Encode.Value
ioK8sApiCoreV1NamespaceEncoder model =
    Encode.object
        [ ( "apiVersion", withDefault Encode.null (map Encode.string model.apiVersion) )
        , ( "kind", withDefault Encode.null (map Encode.string model.kind) )
        , ( "metadata", withDefault Encode.null (map ioK8sApimachineryPkgApisMetaV1ObjectMetaEncoder model.metadata) )
        , ( "spec", withDefault Encode.null (map ioK8sApiCoreV1NamespaceSpecEncoder model.spec) )
        , ( "status", withDefault Encode.null (map ioK8sApiCoreV1NamespaceStatusEncoder model.status) )
        ]


