{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApimachineryPkgApisMetaV1Initializers exposing (IoK8sApimachineryPkgApisMetaV1Initializers, ioK8sApimachineryPkgApisMetaV1InitializersDecoder, ioK8sApimachineryPkgApisMetaV1InitializersEncoder)

import Data.IoK8sApimachineryPkgApisMetaV1Initializer exposing (IoK8sApimachineryPkgApisMetaV1Initializer, ioK8sApimachineryPkgApisMetaV1InitializerDecoder, ioK8sApimachineryPkgApisMetaV1InitializerEncoder)
import Data.IoK8sApimachineryPkgApisMetaV1Status exposing (IoK8sApimachineryPkgApisMetaV1Status, ioK8sApimachineryPkgApisMetaV1StatusDecoder, ioK8sApimachineryPkgApisMetaV1StatusEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   Initializers tracks the progress of initialization.
-}


type alias IoK8sApimachineryPkgApisMetaV1Initializers =
    { pending : (List IoK8sApimachineryPkgApisMetaV1Initializer)
    , result : Maybe IoK8sApimachineryPkgApisMetaV1Status
    }


ioK8sApimachineryPkgApisMetaV1InitializersDecoder : Decoder IoK8sApimachineryPkgApisMetaV1Initializers
ioK8sApimachineryPkgApisMetaV1InitializersDecoder =
    decode IoK8sApimachineryPkgApisMetaV1Initializers
        |> required "pending" (Decode.list ioK8sApimachineryPkgApisMetaV1InitializerDecoder)
        |> optional "result" (Decode.nullable ioK8sApimachineryPkgApisMetaV1StatusDecoder) Nothing



ioK8sApimachineryPkgApisMetaV1InitializersEncoder : IoK8sApimachineryPkgApisMetaV1Initializers -> Encode.Value
ioK8sApimachineryPkgApisMetaV1InitializersEncoder model =
    Encode.object
        [ ( "pending", (Encode.list << List.map ioK8sApimachineryPkgApisMetaV1InitializerEncoder) model.pending )
        , ( "result", withDefault Encode.null (map ioK8sApimachineryPkgApisMetaV1StatusEncoder model.result) )
        ]


