{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiAppsV1beta2DaemonSet exposing (IoK8sApiAppsV1beta2DaemonSet, ioK8sApiAppsV1beta2DaemonSetDecoder, ioK8sApiAppsV1beta2DaemonSetEncoder)

import Data.IoK8sApimachineryPkgApisMetaV1ObjectMeta exposing (IoK8sApimachineryPkgApisMetaV1ObjectMeta, ioK8sApimachineryPkgApisMetaV1ObjectMetaDecoder, ioK8sApimachineryPkgApisMetaV1ObjectMetaEncoder)
import Data.IoK8sApiAppsV1beta2DaemonSetSpec exposing (IoK8sApiAppsV1beta2DaemonSetSpec, ioK8sApiAppsV1beta2DaemonSetSpecDecoder, ioK8sApiAppsV1beta2DaemonSetSpecEncoder)
import Data.IoK8sApiAppsV1beta2DaemonSetStatus exposing (IoK8sApiAppsV1beta2DaemonSetStatus, ioK8sApiAppsV1beta2DaemonSetStatusDecoder, ioK8sApiAppsV1beta2DaemonSetStatusEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   DEPRECATED - This group version of DaemonSet is deprecated by apps/v1/DaemonSet. See the release notes for more information. DaemonSet represents the configuration of a daemon set.
-}


type alias IoK8sApiAppsV1beta2DaemonSet =
    { apiVersion : Maybe String
    , kind : Maybe String
    , metadata : Maybe IoK8sApimachineryPkgApisMetaV1ObjectMeta
    , spec : Maybe IoK8sApiAppsV1beta2DaemonSetSpec
    , status : Maybe IoK8sApiAppsV1beta2DaemonSetStatus
    }


ioK8sApiAppsV1beta2DaemonSetDecoder : Decoder IoK8sApiAppsV1beta2DaemonSet
ioK8sApiAppsV1beta2DaemonSetDecoder =
    decode IoK8sApiAppsV1beta2DaemonSet
        |> optional "apiVersion" (Decode.nullable Decode.string) Nothing
        |> optional "kind" (Decode.nullable Decode.string) Nothing
        |> optional "metadata" (Decode.nullable ioK8sApimachineryPkgApisMetaV1ObjectMetaDecoder) Nothing
        |> optional "spec" (Decode.nullable ioK8sApiAppsV1beta2DaemonSetSpecDecoder) Nothing
        |> optional "status" (Decode.nullable ioK8sApiAppsV1beta2DaemonSetStatusDecoder) Nothing



ioK8sApiAppsV1beta2DaemonSetEncoder : IoK8sApiAppsV1beta2DaemonSet -> Encode.Value
ioK8sApiAppsV1beta2DaemonSetEncoder model =
    Encode.object
        [ ( "apiVersion", withDefault Encode.null (map Encode.string model.apiVersion) )
        , ( "kind", withDefault Encode.null (map Encode.string model.kind) )
        , ( "metadata", withDefault Encode.null (map ioK8sApimachineryPkgApisMetaV1ObjectMetaEncoder model.metadata) )
        , ( "spec", withDefault Encode.null (map ioK8sApiAppsV1beta2DaemonSetSpecEncoder model.spec) )
        , ( "status", withDefault Encode.null (map ioK8sApiAppsV1beta2DaemonSetStatusEncoder model.status) )
        ]


