{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiAuthorizationV1beta1SelfSubjectAccessReview exposing (IoK8sApiAuthorizationV1beta1SelfSubjectAccessReview, ioK8sApiAuthorizationV1beta1SelfSubjectAccessReviewDecoder, ioK8sApiAuthorizationV1beta1SelfSubjectAccessReviewEncoder)

import Data.IoK8sApimachineryPkgApisMetaV1ObjectMeta exposing (IoK8sApimachineryPkgApisMetaV1ObjectMeta, ioK8sApimachineryPkgApisMetaV1ObjectMetaDecoder, ioK8sApimachineryPkgApisMetaV1ObjectMetaEncoder)
import Data.IoK8sApiAuthorizationV1beta1SelfSubjectAccessReviewSpec exposing (IoK8sApiAuthorizationV1beta1SelfSubjectAccessReviewSpec, ioK8sApiAuthorizationV1beta1SelfSubjectAccessReviewSpecDecoder, ioK8sApiAuthorizationV1beta1SelfSubjectAccessReviewSpecEncoder)
import Data.IoK8sApiAuthorizationV1beta1SubjectAccessReviewStatus exposing (IoK8sApiAuthorizationV1beta1SubjectAccessReviewStatus, ioK8sApiAuthorizationV1beta1SubjectAccessReviewStatusDecoder, ioK8sApiAuthorizationV1beta1SubjectAccessReviewStatusEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   SelfSubjectAccessReview checks whether or the current user can perform an action.  Not filling in a spec.namespace means \"in all namespaces\".  Self is a special case, because users should always be able to check whether they can perform an action
-}


type alias IoK8sApiAuthorizationV1beta1SelfSubjectAccessReview =
    { apiVersion : Maybe String
    , kind : Maybe String
    , metadata : Maybe IoK8sApimachineryPkgApisMetaV1ObjectMeta
    , spec : IoK8sApiAuthorizationV1beta1SelfSubjectAccessReviewSpec
    , status : Maybe IoK8sApiAuthorizationV1beta1SubjectAccessReviewStatus
    }


ioK8sApiAuthorizationV1beta1SelfSubjectAccessReviewDecoder : Decoder IoK8sApiAuthorizationV1beta1SelfSubjectAccessReview
ioK8sApiAuthorizationV1beta1SelfSubjectAccessReviewDecoder =
    decode IoK8sApiAuthorizationV1beta1SelfSubjectAccessReview
        |> optional "apiVersion" (Decode.nullable Decode.string) Nothing
        |> optional "kind" (Decode.nullable Decode.string) Nothing
        |> optional "metadata" (Decode.nullable ioK8sApimachineryPkgApisMetaV1ObjectMetaDecoder) Nothing
        |> required "spec" ioK8sApiAuthorizationV1beta1SelfSubjectAccessReviewSpecDecoder
        |> optional "status" (Decode.nullable ioK8sApiAuthorizationV1beta1SubjectAccessReviewStatusDecoder) Nothing



ioK8sApiAuthorizationV1beta1SelfSubjectAccessReviewEncoder : IoK8sApiAuthorizationV1beta1SelfSubjectAccessReview -> Encode.Value
ioK8sApiAuthorizationV1beta1SelfSubjectAccessReviewEncoder model =
    Encode.object
        [ ( "apiVersion", withDefault Encode.null (map Encode.string model.apiVersion) )
        , ( "kind", withDefault Encode.null (map Encode.string model.kind) )
        , ( "metadata", withDefault Encode.null (map ioK8sApimachineryPkgApisMetaV1ObjectMetaEncoder model.metadata) )
        , ( "spec", ioK8sApiAuthorizationV1beta1SelfSubjectAccessReviewSpecEncoder model.spec )
        , ( "status", withDefault Encode.null (map ioK8sApiAuthorizationV1beta1SubjectAccessReviewStatusEncoder model.status) )
        ]


