{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiAppsV1ReplicaSetSpec exposing (IoK8sApiAppsV1ReplicaSetSpec, ioK8sApiAppsV1ReplicaSetSpecDecoder, ioK8sApiAppsV1ReplicaSetSpecEncoder)

import Data.IoK8sApimachineryPkgApisMetaV1LabelSelector exposing (IoK8sApimachineryPkgApisMetaV1LabelSelector, ioK8sApimachineryPkgApisMetaV1LabelSelectorDecoder, ioK8sApimachineryPkgApisMetaV1LabelSelectorEncoder)
import Data.IoK8sApiCoreV1PodTemplateSpec exposing (IoK8sApiCoreV1PodTemplateSpec, ioK8sApiCoreV1PodTemplateSpecDecoder, ioK8sApiCoreV1PodTemplateSpecEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   ReplicaSetSpec is the specification of a ReplicaSet.
-}


type alias IoK8sApiAppsV1ReplicaSetSpec =
    { minReadySeconds : Maybe Int
    , replicas : Maybe Int
    , selector : IoK8sApimachineryPkgApisMetaV1LabelSelector
    , template : Maybe IoK8sApiCoreV1PodTemplateSpec
    }


ioK8sApiAppsV1ReplicaSetSpecDecoder : Decoder IoK8sApiAppsV1ReplicaSetSpec
ioK8sApiAppsV1ReplicaSetSpecDecoder =
    decode IoK8sApiAppsV1ReplicaSetSpec
        |> optional "minReadySeconds" (Decode.nullable Decode.int) Nothing
        |> optional "replicas" (Decode.nullable Decode.int) Nothing
        |> required "selector" ioK8sApimachineryPkgApisMetaV1LabelSelectorDecoder
        |> optional "template" (Decode.nullable ioK8sApiCoreV1PodTemplateSpecDecoder) Nothing



ioK8sApiAppsV1ReplicaSetSpecEncoder : IoK8sApiAppsV1ReplicaSetSpec -> Encode.Value
ioK8sApiAppsV1ReplicaSetSpecEncoder model =
    Encode.object
        [ ( "minReadySeconds", withDefault Encode.null (map Encode.int model.minReadySeconds) )
        , ( "replicas", withDefault Encode.null (map Encode.int model.replicas) )
        , ( "selector", ioK8sApimachineryPkgApisMetaV1LabelSelectorEncoder model.selector )
        , ( "template", withDefault Encode.null (map ioK8sApiCoreV1PodTemplateSpecEncoder model.template) )
        ]


