{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sKubernetesPkgApisCertificatesV1beta1CertificateSigningRequestList exposing (IoK8sKubernetesPkgApisCertificatesV1beta1CertificateSigningRequestList, ioK8sKubernetesPkgApisCertificatesV1beta1CertificateSigningRequestListDecoder, ioK8sKubernetesPkgApisCertificatesV1beta1CertificateSigningRequestListEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)




type alias IoK8sKubernetesPkgApisCertificatesV1beta1CertificateSigningRequestList =
    {     }


ioK8sKubernetesPkgApisCertificatesV1beta1CertificateSigningRequestListDecoder : Decoder IoK8sKubernetesPkgApisCertificatesV1beta1CertificateSigningRequestList
ioK8sKubernetesPkgApisCertificatesV1beta1CertificateSigningRequestListDecoder =
    decode IoK8sKubernetesPkgApisCertificatesV1beta1CertificateSigningRequestList



ioK8sKubernetesPkgApisCertificatesV1beta1CertificateSigningRequestListEncoder : IoK8sKubernetesPkgApisCertificatesV1beta1CertificateSigningRequestList -> Encode.Value
ioK8sKubernetesPkgApisCertificatesV1beta1CertificateSigningRequestListEncoder model =
    Encode.object
        ]


