{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiCertificatesV1beta1CertificateSigningRequestSpec exposing (IoK8sApiCertificatesV1beta1CertificateSigningRequestSpec, ioK8sApiCertificatesV1beta1CertificateSigningRequestSpecDecoder, ioK8sApiCertificatesV1beta1CertificateSigningRequestSpecEncoder)

import Data.List exposing (List, stringDecoder, stringEncoder)
import Byte exposing (Byte, byteDecoder, byteEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   This information is immutable after the request is created. Only the Request and Usages fields can be set on creation, other fields are derived by Kubernetes and cannot be modified by users.
-}


type alias IoK8sApiCertificatesV1beta1CertificateSigningRequestSpec =
    { extra : Maybe (List String)
    , groups : Maybe (List String)
    , request : Byte
    , uid : Maybe String
    , usages : Maybe (List String)
    , username : Maybe String
    }


ioK8sApiCertificatesV1beta1CertificateSigningRequestSpecDecoder : Decoder IoK8sApiCertificatesV1beta1CertificateSigningRequestSpec
ioK8sApiCertificatesV1beta1CertificateSigningRequestSpecDecoder =
    decode IoK8sApiCertificatesV1beta1CertificateSigningRequestSpec
        |> optional "extra" (Decode.nullable (Decode.list stringDecoder)) Nothing
        |> optional "groups" (Decode.nullable (Decode.list Decode.string)) Nothing
        |> required "request" byteDecoder
        |> optional "uid" (Decode.nullable Decode.string) Nothing
        |> optional "usages" (Decode.nullable (Decode.list Decode.string)) Nothing
        |> optional "username" (Decode.nullable Decode.string) Nothing



ioK8sApiCertificatesV1beta1CertificateSigningRequestSpecEncoder : IoK8sApiCertificatesV1beta1CertificateSigningRequestSpec -> Encode.Value
ioK8sApiCertificatesV1beta1CertificateSigningRequestSpecEncoder model =
    Encode.object
        [ ( "extra", withDefault Encode.null (map (Encode.list << List.map stringEncoder) model.extra) )
        , ( "groups", withDefault Encode.null (map (Encode.list << List.map Encode.string) model.groups) )
        , ( "request", byteEncoder model.request )
        , ( "uid", withDefault Encode.null (map Encode.string model.uid) )
        , ( "usages", withDefault Encode.null (map (Encode.list << List.map Encode.string) model.usages) )
        , ( "username", withDefault Encode.null (map Encode.string model.username) )
        ]


