{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiExtensionsV1beta1ReplicaSetList exposing (IoK8sApiExtensionsV1beta1ReplicaSetList, ioK8sApiExtensionsV1beta1ReplicaSetListDecoder, ioK8sApiExtensionsV1beta1ReplicaSetListEncoder)

import Data.IoK8sApiExtensionsV1beta1ReplicaSet exposing (IoK8sApiExtensionsV1beta1ReplicaSet, ioK8sApiExtensionsV1beta1ReplicaSetDecoder, ioK8sApiExtensionsV1beta1ReplicaSetEncoder)
import Data.IoK8sApimachineryPkgApisMetaV1ListMeta exposing (IoK8sApimachineryPkgApisMetaV1ListMeta, ioK8sApimachineryPkgApisMetaV1ListMetaDecoder, ioK8sApimachineryPkgApisMetaV1ListMetaEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   ReplicaSetList is a collection of ReplicaSets.
-}


type alias IoK8sApiExtensionsV1beta1ReplicaSetList =
    { apiVersion : Maybe String
    , items : (List IoK8sApiExtensionsV1beta1ReplicaSet)
    , kind : Maybe String
    , metadata : Maybe IoK8sApimachineryPkgApisMetaV1ListMeta
    }


ioK8sApiExtensionsV1beta1ReplicaSetListDecoder : Decoder IoK8sApiExtensionsV1beta1ReplicaSetList
ioK8sApiExtensionsV1beta1ReplicaSetListDecoder =
    decode IoK8sApiExtensionsV1beta1ReplicaSetList
        |> optional "apiVersion" (Decode.nullable Decode.string) Nothing
        |> required "items" (Decode.list ioK8sApiExtensionsV1beta1ReplicaSetDecoder)
        |> optional "kind" (Decode.nullable Decode.string) Nothing
        |> optional "metadata" (Decode.nullable ioK8sApimachineryPkgApisMetaV1ListMetaDecoder) Nothing



ioK8sApiExtensionsV1beta1ReplicaSetListEncoder : IoK8sApiExtensionsV1beta1ReplicaSetList -> Encode.Value
ioK8sApiExtensionsV1beta1ReplicaSetListEncoder model =
    Encode.object
        [ ( "apiVersion", withDefault Encode.null (map Encode.string model.apiVersion) )
        , ( "items", (Encode.list << List.map ioK8sApiExtensionsV1beta1ReplicaSetEncoder) model.items )
        , ( "kind", withDefault Encode.null (map Encode.string model.kind) )
        , ( "metadata", withDefault Encode.null (map ioK8sApimachineryPkgApisMetaV1ListMetaEncoder model.metadata) )
        ]


