{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiCoreV1ConfigMapNodeConfigSource exposing (IoK8sApiCoreV1ConfigMapNodeConfigSource, ioK8sApiCoreV1ConfigMapNodeConfigSourceDecoder, ioK8sApiCoreV1ConfigMapNodeConfigSourceEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   ConfigMapNodeConfigSource contains the information to reference a ConfigMap as a config source for the Node.
-}


type alias IoK8sApiCoreV1ConfigMapNodeConfigSource =
    { kubeletConfigKey : String
    , name : String
    , namespace : String
    , resourceVersion : Maybe String
    , uid : Maybe String
    }


ioK8sApiCoreV1ConfigMapNodeConfigSourceDecoder : Decoder IoK8sApiCoreV1ConfigMapNodeConfigSource
ioK8sApiCoreV1ConfigMapNodeConfigSourceDecoder =
    decode IoK8sApiCoreV1ConfigMapNodeConfigSource
        |> required "kubeletConfigKey" Decode.string
        |> required "name" Decode.string
        |> required "namespace" Decode.string
        |> optional "resourceVersion" (Decode.nullable Decode.string) Nothing
        |> optional "uid" (Decode.nullable Decode.string) Nothing



ioK8sApiCoreV1ConfigMapNodeConfigSourceEncoder : IoK8sApiCoreV1ConfigMapNodeConfigSource -> Encode.Value
ioK8sApiCoreV1ConfigMapNodeConfigSourceEncoder model =
    Encode.object
        [ ( "kubeletConfigKey", Encode.string model.kubeletConfigKey )
        , ( "name", Encode.string model.name )
        , ( "namespace", Encode.string model.namespace )
        , ( "resourceVersion", withDefault Encode.null (map Encode.string model.resourceVersion) )
        , ( "uid", withDefault Encode.null (map Encode.string model.uid) )
        ]


