{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApimachineryPkgApisMetaV1Patch exposing (IoK8sApimachineryPkgApisMetaV1Patch, ioK8sApimachineryPkgApisMetaV1PatchDecoder, ioK8sApimachineryPkgApisMetaV1PatchEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   Patch is provided to give a concrete name and type to the Kubernetes PATCH request body.
-}


type alias IoK8sApimachineryPkgApisMetaV1Patch =
    {     }


ioK8sApimachineryPkgApisMetaV1PatchDecoder : Decoder IoK8sApimachineryPkgApisMetaV1Patch
ioK8sApimachineryPkgApisMetaV1PatchDecoder =
    decode IoK8sApimachineryPkgApisMetaV1Patch



ioK8sApimachineryPkgApisMetaV1PatchEncoder : IoK8sApimachineryPkgApisMetaV1Patch -> Encode.Value
ioK8sApimachineryPkgApisMetaV1PatchEncoder model =
    Encode.object
        ]


