{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiCoreV1QuobyteVolumeSource exposing (IoK8sApiCoreV1QuobyteVolumeSource, ioK8sApiCoreV1QuobyteVolumeSourceDecoder, ioK8sApiCoreV1QuobyteVolumeSourceEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   Represents a Quobyte mount that lasts the lifetime of a pod. Quobyte volumes do not support ownership management or SELinux relabeling.
-}


type alias IoK8sApiCoreV1QuobyteVolumeSource =
    { group : Maybe String
    , readOnly : Maybe Bool
    , registry : String
    , user : Maybe String
    , volume : String
    }


ioK8sApiCoreV1QuobyteVolumeSourceDecoder : Decoder IoK8sApiCoreV1QuobyteVolumeSource
ioK8sApiCoreV1QuobyteVolumeSourceDecoder =
    decode IoK8sApiCoreV1QuobyteVolumeSource
        |> optional "group" (Decode.nullable Decode.string) Nothing
        |> optional "readOnly" (Decode.nullable Decode.bool) Nothing
        |> required "registry" Decode.string
        |> optional "user" (Decode.nullable Decode.string) Nothing
        |> required "volume" Decode.string



ioK8sApiCoreV1QuobyteVolumeSourceEncoder : IoK8sApiCoreV1QuobyteVolumeSource -> Encode.Value
ioK8sApiCoreV1QuobyteVolumeSourceEncoder model =
    Encode.object
        [ ( "group", withDefault Encode.null (map Encode.string model.group) )
        , ( "readOnly", withDefault Encode.null (map Encode.bool model.readOnly) )
        , ( "registry", Encode.string model.registry )
        , ( "user", withDefault Encode.null (map Encode.string model.user) )
        , ( "volume", Encode.string model.volume )
        ]


