{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiCoreV1NodeAddress exposing (IoK8sApiCoreV1NodeAddress, ioK8sApiCoreV1NodeAddressDecoder, ioK8sApiCoreV1NodeAddressEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   NodeAddress contains information for the node's address.
-}


type alias IoK8sApiCoreV1NodeAddress =
    { address : String
    , type_ : String
    }


ioK8sApiCoreV1NodeAddressDecoder : Decoder IoK8sApiCoreV1NodeAddress
ioK8sApiCoreV1NodeAddressDecoder =
    decode IoK8sApiCoreV1NodeAddress
        |> required "address" Decode.string
        |> required "type" Decode.string



ioK8sApiCoreV1NodeAddressEncoder : IoK8sApiCoreV1NodeAddress -> Encode.Value
ioK8sApiCoreV1NodeAddressEncoder model =
    Encode.object
        [ ( "address", Encode.string model.address )
        , ( "type", Encode.string model.type_ )
        ]


