{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiCoreV1EventSource exposing (IoK8sApiCoreV1EventSource, ioK8sApiCoreV1EventSourceDecoder, ioK8sApiCoreV1EventSourceEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   EventSource contains information for an event.
-}


type alias IoK8sApiCoreV1EventSource =
    { component : Maybe String
    , host : Maybe String
    }


ioK8sApiCoreV1EventSourceDecoder : Decoder IoK8sApiCoreV1EventSource
ioK8sApiCoreV1EventSourceDecoder =
    decode IoK8sApiCoreV1EventSource
        |> optional "component" (Decode.nullable Decode.string) Nothing
        |> optional "host" (Decode.nullable Decode.string) Nothing



ioK8sApiCoreV1EventSourceEncoder : IoK8sApiCoreV1EventSource -> Encode.Value
ioK8sApiCoreV1EventSourceEncoder model =
    Encode.object
        [ ( "component", withDefault Encode.null (map Encode.string model.component) )
        , ( "host", withDefault Encode.null (map Encode.string model.host) )
        ]


