{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerStatus exposing (IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerStatus, ioK8sApiAutoscalingV2beta2HorizontalPodAutoscalerStatusDecoder, ioK8sApiAutoscalingV2beta2HorizontalPodAutoscalerStatusEncoder)

import Data.IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerCondition exposing (IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerCondition, ioK8sApiAutoscalingV2beta2HorizontalPodAutoscalerConditionDecoder, ioK8sApiAutoscalingV2beta2HorizontalPodAutoscalerConditionEncoder)
import Data.IoK8sApiAutoscalingV2beta2MetricStatus exposing (IoK8sApiAutoscalingV2beta2MetricStatus, ioK8sApiAutoscalingV2beta2MetricStatusDecoder, ioK8sApiAutoscalingV2beta2MetricStatusEncoder)
import Data.IoK8sApimachineryPkgApisMetaV1Time exposing (IoK8sApimachineryPkgApisMetaV1Time, ioK8sApimachineryPkgApisMetaV1TimeDecoder, ioK8sApimachineryPkgApisMetaV1TimeEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   HorizontalPodAutoscalerStatus describes the current status of a horizontal pod autoscaler.
-}


type alias IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerStatus =
    { conditions : (List IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerCondition)
    , currentMetrics : Maybe (List IoK8sApiAutoscalingV2beta2MetricStatus)
    , currentReplicas : Int
    , desiredReplicas : Int
    , lastScaleTime : Maybe IoK8sApimachineryPkgApisMetaV1Time
    , observedGeneration : Maybe Int
    }


ioK8sApiAutoscalingV2beta2HorizontalPodAutoscalerStatusDecoder : Decoder IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerStatus
ioK8sApiAutoscalingV2beta2HorizontalPodAutoscalerStatusDecoder =
    decode IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerStatus
        |> required "conditions" (Decode.list ioK8sApiAutoscalingV2beta2HorizontalPodAutoscalerConditionDecoder)
        |> optional "currentMetrics" (Decode.nullable (Decode.list ioK8sApiAutoscalingV2beta2MetricStatusDecoder)) Nothing
        |> required "currentReplicas" Decode.int
        |> required "desiredReplicas" Decode.int
        |> optional "lastScaleTime" (Decode.nullable ioK8sApimachineryPkgApisMetaV1TimeDecoder) Nothing
        |> optional "observedGeneration" (Decode.nullable Decode.int) Nothing



ioK8sApiAutoscalingV2beta2HorizontalPodAutoscalerStatusEncoder : IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerStatus -> Encode.Value
ioK8sApiAutoscalingV2beta2HorizontalPodAutoscalerStatusEncoder model =
    Encode.object
        [ ( "conditions", (Encode.list << List.map ioK8sApiAutoscalingV2beta2HorizontalPodAutoscalerConditionEncoder) model.conditions )
        , ( "currentMetrics", withDefault Encode.null (map (Encode.list << List.map ioK8sApiAutoscalingV2beta2MetricStatusEncoder) model.currentMetrics) )
        , ( "currentReplicas", Encode.int model.currentReplicas )
        , ( "desiredReplicas", Encode.int model.desiredReplicas )
        , ( "lastScaleTime", withDefault Encode.null (map ioK8sApimachineryPkgApisMetaV1TimeEncoder model.lastScaleTime) )
        , ( "observedGeneration", withDefault Encode.null (map Encode.int model.observedGeneration) )
        ]


