{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiAuditregistrationV1alpha1ServiceReference exposing (IoK8sApiAuditregistrationV1alpha1ServiceReference, ioK8sApiAuditregistrationV1alpha1ServiceReferenceDecoder, ioK8sApiAuditregistrationV1alpha1ServiceReferenceEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   ServiceReference holds a reference to Service.legacy.k8s.io
-}


type alias IoK8sApiAuditregistrationV1alpha1ServiceReference =
    { name : String
    , namespace : String
    , path : Maybe String
    }


ioK8sApiAuditregistrationV1alpha1ServiceReferenceDecoder : Decoder IoK8sApiAuditregistrationV1alpha1ServiceReference
ioK8sApiAuditregistrationV1alpha1ServiceReferenceDecoder =
    decode IoK8sApiAuditregistrationV1alpha1ServiceReference
        |> required "name" Decode.string
        |> required "namespace" Decode.string
        |> optional "path" (Decode.nullable Decode.string) Nothing



ioK8sApiAuditregistrationV1alpha1ServiceReferenceEncoder : IoK8sApiAuditregistrationV1alpha1ServiceReference -> Encode.Value
ioK8sApiAuditregistrationV1alpha1ServiceReferenceEncoder model =
    Encode.object
        [ ( "name", Encode.string model.name )
        , ( "namespace", Encode.string model.namespace )
        , ( "path", withDefault Encode.null (map Encode.string model.path) )
        ]


