{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiCoreV1SecretReference exposing (IoK8sApiCoreV1SecretReference, ioK8sApiCoreV1SecretReferenceDecoder, ioK8sApiCoreV1SecretReferenceEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   SecretReference represents a Secret Reference. It has enough information to retrieve secret in any namespace
-}


type alias IoK8sApiCoreV1SecretReference =
    { name : Maybe String
    , namespace : Maybe String
    }


ioK8sApiCoreV1SecretReferenceDecoder : Decoder IoK8sApiCoreV1SecretReference
ioK8sApiCoreV1SecretReferenceDecoder =
    decode IoK8sApiCoreV1SecretReference
        |> optional "name" (Decode.nullable Decode.string) Nothing
        |> optional "namespace" (Decode.nullable Decode.string) Nothing



ioK8sApiCoreV1SecretReferenceEncoder : IoK8sApiCoreV1SecretReference -> Encode.Value
ioK8sApiCoreV1SecretReferenceEncoder model =
    Encode.object
        [ ( "name", withDefault Encode.null (map Encode.string model.name) )
        , ( "namespace", withDefault Encode.null (map Encode.string model.namespace) )
        ]


