{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiNetworkingV1NetworkPolicySpec exposing (IoK8sApiNetworkingV1NetworkPolicySpec, ioK8sApiNetworkingV1NetworkPolicySpecDecoder, ioK8sApiNetworkingV1NetworkPolicySpecEncoder)

import Data.IoK8sApiNetworkingV1NetworkPolicyEgressRule exposing (IoK8sApiNetworkingV1NetworkPolicyEgressRule, ioK8sApiNetworkingV1NetworkPolicyEgressRuleDecoder, ioK8sApiNetworkingV1NetworkPolicyEgressRuleEncoder)
import Data.IoK8sApiNetworkingV1NetworkPolicyIngressRule exposing (IoK8sApiNetworkingV1NetworkPolicyIngressRule, ioK8sApiNetworkingV1NetworkPolicyIngressRuleDecoder, ioK8sApiNetworkingV1NetworkPolicyIngressRuleEncoder)
import Data.IoK8sApimachineryPkgApisMetaV1LabelSelector exposing (IoK8sApimachineryPkgApisMetaV1LabelSelector, ioK8sApimachineryPkgApisMetaV1LabelSelectorDecoder, ioK8sApimachineryPkgApisMetaV1LabelSelectorEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   NetworkPolicySpec provides the specification of a NetworkPolicy
-}


type alias IoK8sApiNetworkingV1NetworkPolicySpec =
    { egress : Maybe (List IoK8sApiNetworkingV1NetworkPolicyEgressRule)
    , ingress : Maybe (List IoK8sApiNetworkingV1NetworkPolicyIngressRule)
    , podSelector : IoK8sApimachineryPkgApisMetaV1LabelSelector
    , policyTypes : Maybe (List String)
    }


ioK8sApiNetworkingV1NetworkPolicySpecDecoder : Decoder IoK8sApiNetworkingV1NetworkPolicySpec
ioK8sApiNetworkingV1NetworkPolicySpecDecoder =
    decode IoK8sApiNetworkingV1NetworkPolicySpec
        |> optional "egress" (Decode.nullable (Decode.list ioK8sApiNetworkingV1NetworkPolicyEgressRuleDecoder)) Nothing
        |> optional "ingress" (Decode.nullable (Decode.list ioK8sApiNetworkingV1NetworkPolicyIngressRuleDecoder)) Nothing
        |> required "podSelector" ioK8sApimachineryPkgApisMetaV1LabelSelectorDecoder
        |> optional "policyTypes" (Decode.nullable (Decode.list Decode.string)) Nothing



ioK8sApiNetworkingV1NetworkPolicySpecEncoder : IoK8sApiNetworkingV1NetworkPolicySpec -> Encode.Value
ioK8sApiNetworkingV1NetworkPolicySpecEncoder model =
    Encode.object
        [ ( "egress", withDefault Encode.null (map (Encode.list << List.map ioK8sApiNetworkingV1NetworkPolicyEgressRuleEncoder) model.egress) )
        , ( "ingress", withDefault Encode.null (map (Encode.list << List.map ioK8sApiNetworkingV1NetworkPolicyIngressRuleEncoder) model.ingress) )
        , ( "podSelector", ioK8sApimachineryPkgApisMetaV1LabelSelectorEncoder model.podSelector )
        , ( "policyTypes", withDefault Encode.null (map (Encode.list << List.map Encode.string) model.policyTypes) )
        ]


