{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiAuditregistrationV1alpha1WebhookClientConfig exposing (IoK8sApiAuditregistrationV1alpha1WebhookClientConfig, ioK8sApiAuditregistrationV1alpha1WebhookClientConfigDecoder, ioK8sApiAuditregistrationV1alpha1WebhookClientConfigEncoder)

import Byte exposing (Byte, byteDecoder, byteEncoder)
import Data.IoK8sApiAuditregistrationV1alpha1ServiceReference exposing (IoK8sApiAuditregistrationV1alpha1ServiceReference, ioK8sApiAuditregistrationV1alpha1ServiceReferenceDecoder, ioK8sApiAuditregistrationV1alpha1ServiceReferenceEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   WebhookClientConfig contains the information to make a connection with the webhook
-}


type alias IoK8sApiAuditregistrationV1alpha1WebhookClientConfig =
    { caBundle : Maybe Byte
    , service : Maybe IoK8sApiAuditregistrationV1alpha1ServiceReference
    , url : Maybe String
    }


ioK8sApiAuditregistrationV1alpha1WebhookClientConfigDecoder : Decoder IoK8sApiAuditregistrationV1alpha1WebhookClientConfig
ioK8sApiAuditregistrationV1alpha1WebhookClientConfigDecoder =
    decode IoK8sApiAuditregistrationV1alpha1WebhookClientConfig
        |> optional "caBundle" (Decode.nullable byteDecoder) Nothing
        |> optional "service" (Decode.nullable ioK8sApiAuditregistrationV1alpha1ServiceReferenceDecoder) Nothing
        |> optional "url" (Decode.nullable Decode.string) Nothing



ioK8sApiAuditregistrationV1alpha1WebhookClientConfigEncoder : IoK8sApiAuditregistrationV1alpha1WebhookClientConfig -> Encode.Value
ioK8sApiAuditregistrationV1alpha1WebhookClientConfigEncoder model =
    Encode.object
        [ ( "caBundle", withDefault Encode.null (map byteEncoder model.caBundle) )
        , ( "service", withDefault Encode.null (map ioK8sApiAuditregistrationV1alpha1ServiceReferenceEncoder model.service) )
        , ( "url", withDefault Encode.null (map Encode.string model.url) )
        ]


