{-
   Kubernetes
   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: v1.14.0
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.IoK8sApiPolicyV1beta1SupplementalGroupsStrategyOptions exposing (IoK8sApiPolicyV1beta1SupplementalGroupsStrategyOptions, ioK8sApiPolicyV1beta1SupplementalGroupsStrategyOptionsDecoder, ioK8sApiPolicyV1beta1SupplementalGroupsStrategyOptionsEncoder)

import Data.IoK8sApiPolicyV1beta1IDRange exposing (IoK8sApiPolicyV1beta1IDRange, ioK8sApiPolicyV1beta1IDRangeDecoder, ioK8sApiPolicyV1beta1IDRangeEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   SupplementalGroupsStrategyOptions defines the strategy type and options used to create the strategy.
-}


type alias IoK8sApiPolicyV1beta1SupplementalGroupsStrategyOptions =
    { ranges : Maybe (List IoK8sApiPolicyV1beta1IDRange)
    , rule : Maybe String
    }


ioK8sApiPolicyV1beta1SupplementalGroupsStrategyOptionsDecoder : Decoder IoK8sApiPolicyV1beta1SupplementalGroupsStrategyOptions
ioK8sApiPolicyV1beta1SupplementalGroupsStrategyOptionsDecoder =
    decode IoK8sApiPolicyV1beta1SupplementalGroupsStrategyOptions
        |> optional "ranges" (Decode.nullable (Decode.list ioK8sApiPolicyV1beta1IDRangeDecoder)) Nothing
        |> optional "rule" (Decode.nullable Decode.string) Nothing



ioK8sApiPolicyV1beta1SupplementalGroupsStrategyOptionsEncoder : IoK8sApiPolicyV1beta1SupplementalGroupsStrategyOptions -> Encode.Value
ioK8sApiPolicyV1beta1SupplementalGroupsStrategyOptionsEncoder model =
    Encode.object
        [ ( "ranges", withDefault Encode.null (map (Encode.list << List.map ioK8sApiPolicyV1beta1IDRangeEncoder) model.ranges) )
        , ( "rule", withDefault Encode.null (map Encode.string model.rule) )
        ]


